insert into services (sort_order, name, name_en, description, description_en) values
  (1, 'Tham vấn & Trị liệu tâm lý', 'Counseling & Psychotherapy', 'Quá trình điều trị liên tục nhằm giải quyết vấn đề tâm lý, cải thiện sức khỏe tinh thần và phát triển cá nhân, thông qua đối thoại và các kỹ thuật chuyên biệt. Phù hợp cho vấn đề về bản ngã (phát triển bản thân, lòng tự trọng, phong cách gắn bó) và các bệnh lý.', 'An ongoing process to address psychological difficulties, improve mental wellbeing and support personal growth, through dialogue and specialized techniques. Suited to questions of self (personal development, self-esteem, attachment style) and clinical conditions.'),
  (2, 'Đánh giá tâm lý', 'Psychological Assessment', 'Sử dụng các bài kiểm tra và công cụ chuẩn hóa để thu thập thông tin về nhận thức, tính cách, cảm xúc và hành vi. Buổi 60 phút làm việc trực tiếp với therapist — họ chọn bài test phù hợp, kết luận ngay trong buổi và gửi báo cáo PDF chi tiết qua email trong 7–10 ngày.', 'Using standardized tests and tools to gather information about cognition, personality, emotion and behavior. A 60-minute session working directly with a therapist — they choose suitable tests, conclude within the session, and send a detailed PDF report by email within 7–10 days.'),
  (3, 'Tham vấn cặp đôi', 'Couple Counseling', 'Cùng nhau xây dựng mối quan hệ tốt đẹp hơn và làm rõ các vấn đề về giao tiếp, cách thể hiện cảm xúc. Buổi đầu khám phá nhu cầu riêng của mỗi người (30 phút/người), các buổi sau cả hai tham gia cùng nhau (90 phút). Có thể sắp xếp buổi riêng khi cần.', 'Build a better relationship together and clarify issues around communication and expressing emotion. The first session explores each person''s needs (30 min/person); later sessions are joint (90 min). Individual sessions can be arranged when needed.'),
  (4, 'Hướng nghiệp', 'Career Counseling', 'Làm test năng lực + trò chuyện với therapist về định hướng. Gói Cơ bản (2 buổi) gồm test và tư vấn kết quả; gói Chuyên sâu (3 buổi) có thêm buổi lên kế hoạch thực hiện định hướng.', 'Take an aptitude test + talk with a therapist about direction. The Basic package (2 sessions) covers testing and results consultation; the In-depth package (3 sessions) adds a session to plan out your direction.'),
  (5, 'Employee Assistance Program (EAP)', 'Employee Assistance Program (EAP)', 'Đồng hành cùng doanh nghiệp trong việc xây dựng văn hóa quan tâm đến con người thông qua các giải pháp chăm sóc sức khỏe tâm thần dựa trên cơ sở khoa học và phù hợp với bối cảnh thực tiễn.', 'Partnering with organizations to build people-centered workplace cultures through evidence-based mental health solutions tailored to real-world organizational contexts.'),
  (6, 'Low-cost Therapy', 'Low-cost Therapy', 'Chương trình Hỗ trợ (Low-cost Therapy) mang đến giải pháp hỗ trợ thiết thực với mức phí giảm 20% so với thông thường, dành riêng cho học sinh và sinh viên dưới 20 tuổi hoặc các bạn đang gặp khó khăn về tài chính.', 'Our Low-cost Therapy program offers practical mental health support at fees 20% lower than standard rates, exclusively for students under 20 or people experiencing financial hardship.'),
  (7, 'Workshop', 'Workshop', 'Chú trọng sự kết hợp giữa lý thuyết nền tảng và thực hành trải nghiệm, giúp bạn mang về những giá trị ứng dụng thực tế. Dưới sự dẫn dắt của thạc sĩ tâm lý/nhà trị liệu, mỗi buổi học sẽ cung cấp kiến thức chuyên ngành và kỹ năng cụ thể—từ thiết lập ranh giới, nhận diện kiểu gắn bó đến xoa dịu lo âu.', 'Combining foundational theory with experiential practice, each workshop gives you practical tools to apply in everyday life. Led by a master''s-level psychologist or therapist, every session offers specialist knowledge and specific skills—from setting boundaries and recognizing attachment styles to easing anxiety.'),
  (8, 'Open Talk', 'Open Talk', 'Không gian trò chuyện bình đẳng, tự do, không diễn giả hay áp lực phát biểu. Bạn có thể thoải mái lắng nghe hoặc lên tiếng khi sẵn sàng. Mỗi phiên thảo luận đều có chuyên viên tâm lý đồng hành để giữ vững không gian an toàn, bảo mật và nâng đỡ cảm xúc.', 'An open, equal conversation space with no speakers and no pressure to contribute. You are welcome to listen or speak when you feel ready. A mental health professional accompanies each discussion to maintain a safe, confidential and emotionally supportive space.'),
  (9, 'Mentorship in Psychology', 'Mentorship in Psychology', 'Chương trình mentorship dành cho sinh viên Tâm lý muốn khám phá ngành tham vấn - trị liệu qua trải nghiệm thực tế, không phải lý thuyết. 6 buổi để bạn đặt chân vào cơ sở tham vấn thật, tự đánh giá bản thân qua trắc nghiệm chuyên môn, và nghe những câu chuyện nghề nghiệp từ người đang làm nghề. Bạn không cần biết trước câu trả lời, chỉ cần mang theo câu hỏi.', 'A mentorship program for psychology students who want to explore counseling and therapy through hands-on experience, not just theory. Across six sessions, you will step inside a real counseling center, reflect on your fit through professional assessments, and hear career stories directly from practitioners. You do not need to have the answers—just bring your questions.');

insert into therapists (sort_order, name, title, specialties, therapies, price, location, photo_url) values
  (1, 'ThS. Hà Trang', 'Thạc sĩ Tâm lý Lâm sàng · ĐH Xã hội Nga', 'PTSD, ADHD & LGBTQI+', 'CBT · ACT · Neurodiversity · AOP', '650K', 'Online · offline SG', null),
  (2, 'ThS. Ngọc Mai', 'Thạc sĩ Tâm lý Lâm sàng', 'Tổn thương thời thơ ấu, khủng hoảng hiện sinh, lòng tự trọng thấp, rối loạn cảm xúc, vấn đề gắn bó & mối quan hệ', 'Person-Centered · CBT · MiCBT · IFS', '650K', 'Online · offline HN', null),
  (3, 'ThS. Thu Thuỷ', 'Thạc sĩ Tâm lý', 'Thân chủ 20–35: mối quan hệ, childhood trauma, attachment styles, lo âu, stress, trầm cảm. Couple therapy', 'CBT · SFBT · Psychodynamic · Mindfulness', '650K', 'Chỉ online', null),
  (4, 'ThS. Ly Đinh', 'Thạc sĩ Tâm lý', 'PTSD/C-PTSD, đau buồn & mất mát, trải nghiệm tuổi thơ bất lợi, trầm cảm, lo âu', 'CBT · CPT · Person-Centered · ACT · DBT', '650K', 'Chỉ online', null),
  (5, 'ThS. Phương An', 'Thạc sĩ Lâm sàng · ĐH Sussex, Anh', 'Tâm lý học trường học, stress, hướng dẫn hành vi. Chuyên viên tâm lý học đường', 'CBT · MI · MBCT', '650K', 'Online · offline HN', null),
  (6, 'ThS. Kim Ngân', '7 năm kinh nghiệm trị liệu', 'ADHD, sang chấn, rối loạn cảm xúc (lo âu, trầm cảm, lưỡng cực), giá trị bản thân, ranh giới', 'CBT · EFT', '650K', 'Online · offline HN', null),
  (7, 'ThS. Gia Bảo', 'ThS Lâm sàng trẻ em & VTN · ĐHQG HN', 'Trầm cảm, lo âu, OCD, PTSD, rối loạn nhân cách ranh giới', 'CBT · DBT · BA', '650K', 'Online · offline HN', null),
  (8, 'ThS. Mai Nguyen', 'Thạc sĩ Tâm lý', 'Vấn đề mối quan hệ (tình yêu, hôn nhân, gia đình, xã hội). Couple Hàn–Việt bằng tiếng Hàn', 'Psychoanalytic · Client-centered · Gestalt', '650K', 'Chỉ online', null),
  (9, 'ThS. Minh Châu', 'Thạc sĩ Tâm lý', 'Lo âu, trầm cảm, đau buồn – tang chế, khó khăn về mối quan hệ gắn bó', 'Psychoanalysis · Adlerian · Mindfulness · Art', '750K', 'Online · offline HCM', null),
  (10, 'ThS. Đức Minh', 'Trị liệu & Tư vấn · ĐH Western Sydney', 'Thân chủ 18–35: lo âu, trầm cảm, PTSD/C-PTSD, sang chấn liên thế hệ, tổn thương gắn bó. Hỗ trợ ASD, ADHD', 'Person-Centered · IFS · EFIT · MI', '650K', 'Online · offline HCM', null),
  (11, 'ThS. Quỳnh Trang', 'ThS Lâm sàng · ĐHQG HN', 'Thân chủ 10–30: trầm cảm, lo âu, OCD, ám sợ xã hội, PTSD. Couple tuổi trẻ', 'CBT & các kỹ thuật lâm sàng', '600K', 'Online · offline HN', null),
  (12, 'Vi Vương', 'PG Dip Tâm lý · ĐH Wrexham (Anh)', 'Tâm lý ung thư học, khủng hoảng tâm lý, bản sắc & ý nghĩa sống. 4 ngôn ngữ: Việt–Anh–Quan Thoại–Quảng Đông', 'ACT · DBT', '600K', 'Online · offline HCM', null);

-- BEGIN GENERATED THERAPIST PROFILES
do $$
declare
  mapped_profile_count bigint;
  invalid_profile_match_count bigint;
begin
  with profile_match_counts as (
  select v.therapist_name, count(t.id)::bigint as match_count
  from (values
  ('ThS. Đức Minh', 'Nguyễn Đức Minh', 'Xin chào, tôi là Đức Minh, Thạc sĩ Tâm lý Liệu pháp và Tham vấn Tâm lý tại Western Sydney University, tốt nghiệp với thành tích Distinction và Dean’s Merit List Award. Tôi đồng thời là Nhà Tham vấn Tâm lý Thực hành được chứng nhận bởi PACFA – Liên đoàn Trị liệu và Tham vấn Tâm lý Úc, với hơn 750 giờ thực hành lâm sàng trong các môi trường tham vấn học đường và hỗ trợ tâm lý cho người lao động tại Sydney, Úc. Trong quá trình làm việc, tôi có cơ hội đồng hành cùng thanh thiếu niên và người trưởng thành đang trải qua lo âu, trầm cảm, căng thẳng, sang chấn, những tổn thương gắn bó và các khó khăn trong mối quan hệ.

Tôi đặc biệt quan tâm đến những tổn thương có thể hình thành từ các mối quan hệ quan trọng trong cuộc đời và cách chúng tiếp tục ảnh hưởng đến cách một người nhìn nhận bản thân, cảm nhận cảm xúc và kết nối với những người xung quanh. Với tôi, việc hiểu một khó khăn không chỉ nằm ở việc nhìn vào điều đang xảy ra ở hiện tại, mà còn cần đặt nó trong câu chuyện, những mối quan hệ và bối cảnh sống của mỗi người. Vì vậy, tôi sử dụng nền tảng Nhân vị Trọng tâm (Person-Centred Therapy), Hệ thống Gia đình (Family Systems Therapy), Phỏng vấn tạo Động lực (Motivational Interviewing), Liệu pháp Tập trung vào Cảm xúc (Emotionally Focused Therapy) để cùng thân chủ khám phá những nhu cầu, cảm xúc và khuôn mẫu đang ảnh hưởng đến cuộc sống của mình.

Tôi cũng đồng hành cùng các cặp đôi trong những giai đoạn nhiều thay đổi, khi khác biệt về kỳ vọng, tài chính, sự nghiệp, nuôi dạy con cái hay trách nhiệm với gia đình bắt đầu tạo ra khoảng cách giữa hai người. Tôi tin rằng mâu thuẫn không nhất thiết là dấu hiệu một mối quan hệ đã thất bại; đôi khi đó là tín hiệu cho thấy cả hai đang có những nhu cầu chưa được nhìn thấy và lắng nghe.

Với tôi, trị liệu tâm lý trước hết cần là một không gian an toàn, bảo mật và không phán xét, nơi bạn có thể thành thật với những điều khó nói, được lắng nghe và tôn trọng. Từ đó, chúng ta cùng tìm ra cách để bạn hiểu mình sâu sắc hơn, xây dựng những kết nối lành mạnh hơn và từng bước sống một cuộc đời phù hợp với điều mình thực sự coi trọng.', null, null, null, true),
  ('ThS. Thu Thuỷ', 'Nguyễn Thu Thủy', 'Xin chào, tôi là Thu Thuỷ, tốt nghiệp Thạc sĩ Tham vấn tâm lý tại Assumption University, Thái Lan và bắt đầu thực hành tham vấn từ năm 2023. Tôi cũng là thành viên của hiệp hội TCPA (Thailand Counseling Psychology Association). Trong quá trình làm việc, tôi có cơ hội đồng hành cùng các thân chủ trong tham vấn cá nhân, cặp đôi và nhóm, đặc biệt trong những khó khăn liên quan đến mối quan hệ, sang chấn thời thơ ấu, kiểu gắn bó và căng thẳng.

Đối với các bạn du học sinh hay Việt Kiều thì tôi càng hiểu rõ hơn vì bản thân đã từng trải qua và có những trải nghiệm để có thể đồng điệu với các bạn. Đối với các bạn sắp cưới, đã cưới và có con thì tôi lại càng hiểu hơn khi có thể đồng hành cùng bạn đi qua những cột mốc lớn trong cuộc đời.

Ngoài ra, tôi từng tham gia hỗ trợ trị liệu nhóm tại Horizon Rehab, với các chương trình như phòng ngừa tái sử dụng chất và trị liệu nhóm dựa trên nghệ thuật dành cho những người gặp khó khăn về sử dụng chất và sức khỏe tâm thần. Đồng thời, tôi đã đồng hành cùng Wabi Therapy từ những ngày đầu tiên và tiếp tục thực hành tại đây cho đến hiện tại.

Trong tham vấn, tôi kết hợp linh hoạt Psychodynamic, Gestalt, Liệu pháp Nhận thức Hành vi (CBT), Liệu pháp Hành vi Biện chứng (DBT), trị liệu dựa trên nghệ thuật và các phương pháp tiếp cận khác. Tôi không tin rằng có một phương pháp duy nhất phù hợp với tất cả mọi người vì mỗi thân chủ đều có một câu chuyện, một nhịp độ và những nhu cầu rất riêng. Vì vậy, điều tôi quan tâm là cùng bạn tìm ra cách tiếp cận phù hợp nhất với hành trình của mình.

Con đường đến với tâm lý của tôi cũng bắt đầu từ sự tò mò. Trước khi được đào tạo bài bản về Tâm lý, tôi từng tìm hiểu về Reiki (và đạt level I), Tarot, Oracle Cards (từng ứng dụng vào trong tham vấn với vẽ) và những phương pháp chữa lành tự nhiên. Những trải nghiệm đó khơi lên trong tôi nhiều câu hỏi về con người, cảm xúc và quá trình chữa lành để rồi đưa tôi đến với tâm lý học một cách khoa học và chuyên nghiệp hơn.

Với tôi, tham vấn không phải là nơi bạn được “sửa chữa” mà là một không gian để bạn có thể chậm lại, được lắng nghe và nhìn lại chính mình với sự tò mò thay vì phán xét. Chúng ta cùng nói chuyện, thảo luận về một chủ đề nào đó. Không cần gấp gáp, chầm chậm và từ tốn khai mở nút thắt trong lòng. Từ đó, bạn có thể hiểu mình hơn, nhận ra những điều mình thực sự cần và có thêm lựa chọn cho cách mình muốn sống, yêu thương và kết nối với người khác.', null, null, null, true),
  ('ThS. Ngọc Mai', 'Nguyễn Ngọc Mai', 'Xin chào, tôi là Ngọc Mai, Thạc sĩ Tâm lý học chuyên ngành Tâm lý lâm sàng và Cử nhân Tâm lý học chuyên ngành Tham vấn tâm lý tại Trường Đại học Khoa học Xã hội và Nhân văn, Đại học Quốc gia Hà Nội. Tôi bắt đầu thực hành tham vấn và trị liệu tâm lý từ năm 2020, và trong quá trình làm việc, tôi chủ yếu đồng hành cùng những người trẻ từ 18–35 tuổi đang tìm cách hiểu mình hơn, điều chỉnh cảm xúc, xây dựng những mối quan hệ lành mạnh và tìm kiếm một hướng đi phù hợp cho cuộc sống.

Tôi có kinh nghiệm đồng hành với những khó khăn liên quan đến tổn thương và trải nghiệm thời thơ ấu, căng thẳng, lo âu, trầm cảm, lòng tự trọng, tự chỉ trích, khủng hoảng và cảm giác mất phương hướng. Bên cạnh đó, tôi cũng làm việc với những vấn đề về gắn bó, các khuôn mẫu lặp lại trong tình yêu và các mối quan hệ gia đình, cũng như những áp lực trong học tập, công việc, định hướng nghề nghiệp và khủng hoảng sự nghiệp. Trong quá trình trị liệu, tôi linh hoạt kết hợp Trị liệu Nhân vị trọng tâm, Trị liệu Nhận thức Hành vi (CBT), Trị liệu Nhận thức Hành vi kết hợp Chánh niệm (MiCBT) và Hệ thống Gia đình Nội tâm (IFS), tùy thuộc vào nhu cầu, mục tiêu và nhịp độ riêng của từng thân chủ.

Tôi tin rằng bạn là người hiểu rõ nhất cuộc sống của mình và là người quyết định mình muốn đi về đâu. Nếu hành trình ấy giống như việc đi qua một đêm tối, tôi muốn mình giống như một chiếc đèn pin – không đi thay bạn, không quyết định con đường thay bạn, mà giúp bạn nhìn rõ hơn những gì đang ở phía trước.

Với tôi, tìm đến một nhà tâm lý không có nghĩa là bạn yếu đuối hay không thể tự giải quyết vấn đề. Đôi khi, đó chính là một cách để bạn dũng cảm đối diện với những điều mình đã cố gắng chịu đựng một mình quá lâu. Trị liệu không phải là hành trình để trở thành một con người hoàn toàn khác, mà là quá trình hiểu mình hơn, học cách chấp nhận cả những phần dễ tổn thương, tìm lại những nguồn lực vốn có và từng bước xây dựng một cuộc sống phù hợp hơn với chính mình. Tôi hy vọng quá trình đồng hành của chúng ta sẽ giúp bạn không chỉ vượt qua một giai đoạn khó khăn, mà còn dần học được cách trở thành người có thể lắng nghe, thấu hiểu và đồng hành cùng chính mình.', null, null, null, true),
  ('ThS. Minh Châu', 'Minh Châu', 'Xin chào, tôi là Minh Châu, Thạc sĩ Tâm lý học tại Trường Đại học Sư phạm Thành phố Hồ Chí Minh, với 7 năm kinh nghiệm thực hành trong lĩnh vực chăm sóc sức khỏe tâm thần. Trong quá trình làm việc, tôi có cơ hội đồng hành cùng nhiều thân chủ đang trải qua những khó khăn về lo âu, trầm cảm, đau buồn và mất mát, những vấn đề trong mối quan hệ gắn bó cũng như những ảnh hưởng còn kéo dài từ các trải nghiệm bất lợi thời thơ ấu.

Tôi đặc biệt quan tâm đến cách những trải nghiệm trong quá khứ có thể tiếp tục hiện diện trong đời sống hiện tại của mỗi người – qua cách chúng ta nhìn nhận bản thân, cảm nhận và điều hòa cảm xúc, xây dựng các mối quan hệ hay phản ứng trước những tình huống quen thuộc. Vì vậy, trong quá trình đồng hành, tôi không chỉ quan tâm đến điều đang khiến bạn khó khăn ở hiện tại, mà còn cùng bạn từ từ khám phá những câu chuyện, nhu cầu và trải nghiệm phía sau những điều ấy.

Về phương pháp, tôi thực hành theo hướng tích hợp, lấy nền tảng từ Phân tâm học (Psychoanalytic) và linh hoạt kết hợp các góc nhìn từ Tâm lý học Adler (Adlerian), thực hành Chú tâm (Mindfulness), sử dụng nghệ thuật như công cụ biểu đạt (art-based methods). Tôi tin rằng mỗi người có một câu chuyện riêng, vì vậy trị liệu cũng cần được điều chỉnh theo nhu cầu, khả năng và nhịp độ của từng thân chủ thay vì áp dụng một công thức giống nhau cho tất cả.

Với tôi, tham vấn tâm lý trước hết là một mối quan hệ an toàn, là không gian lắng nghe thấu đáo và không phán xét để bạn chậm lại, gọi tên và khám phá bất kỳ khía cạnh nào liên quan nhất đến sự an lành của mình — kể cả những bối rối hay nỗi đau sâu kín chưa thể gọi tên. Tôi mong muốn đồng hành cùng bạn để từng bước thấu hiểu, chấp nhận chính bản thân và sẵn sàng kết nối lành mạnh với cuộc sống.', null, null, null, true),
  ('ThS. Ly Đinh', 'Đinh Y Ly', 'Xin chào.

Tôi là Ly, là một thạc sĩ tâm lí (lâm sàng) được đào tạo từ trường ĐH KHXH&NV, ĐHQG Hà Nội với hơn 6 năm kinh nghiệm làm việc trong lĩnh vực tâm lí, bao gồm cung cấp dịch vụ đánh giá, tham vấn và trị liệu tâm lí cho các khách hàng cá nhân.

Từ những trải nghiệm cá nhân kết hợp với quá trình học tập, nghiên cứu và thực hành, tôi đã xác định và phát triển chuyên môn theo định hướng làm việc với các thân chủ là người trưởng thành mang những nỗi đau từ các trải nghiệm bất lợi, tổn thương, sang chấn thời thơ ấu. Các tổn thương đó có thể biểu hiện thành những rối loạn như trầm cảm, lo âu, cũng có thể ảnh hưởng đến lòng tự trọng, cách mỗi người nhìn nhận và đánh giá bản thân, lối hành xử và tương tác trong các mối quan hệ với người khác. Vì vậy, đây không phải một quá trình dễ dàng và nhanh chóng, nhưng tôi tin rằng mình đủ kiên nhẫn, kiến thức và trải nghiệm để đồng hành cùng bạn đi đến cuối hành trình khám phá và tự hàn gắn này.

Trong quá trình làm việc, tôi sử dụng kết hợp liệu pháp CBT với các triết lí và kĩ thuật về thân chủ trọng tâm, chánh niệm, chấp nhận và cam kết (ACT). Tuy vậy, đối với tôi, trị liệu tâm lí không chỉ là thực hành các liệu pháp hay kĩ thuật, mà đó là quá trình một người mở rộng vùng trải nghiệm của mình, thêm vào đó các trải nghiệm tích cực như được chấp nhận vô điều kiện, được lắng nghe, được nhìn thấy, được sự an toàn, được thử, được sai, được thử lại... Từ đó, bạn có thể dấn thân vào cuộc sống và các mối quan hệ, nhìn nhận các giá trị của bản thân, lấy lại sự tự chủ, tự do, niềm tin vào chính mình để hướng tới một cuộc sống bình an, độc lập.

Ngoài ra, tôi cũng đồng hành và hỗ trợ những người đang trải qua đau buồn và mất mát – dù đó là sự ra đi của người thân, thú cưng, chia tay mối quan hệ hay việc phải đối diện với bệnh tật và những thay đổi lớn trong cuộc sống. Đây đều là những trải nghiệm không dễ dàng, và bạn hoàn toàn có quyền lựa chọn không phải trải qua chúng một mình. Các phiên làm việc đều là không gian an toàn để bạn có thể từng bước nhìn nhận và xử lý những cảm xúc bạn đang trải qua, giải tỏa những điều còn dồn nén, thích nghi và dần tìm lại sự cân bằng trong cuộc sống.

Thực hành của tôi đều dựa trên các nguyên tắc đạo đức nghề nghiệp, sự tôn trọng và tin tưởng đối với mỗi thân chủ của mình. Mọi hoạt động hỗ trợ đều hướng đến lợi ích, nhu cầu và sự an toàn của chính bạn.', null, null, null, true),
  ('ThS. Quỳnh Trang', 'Ngọ Quỳnh Trang', 'Mình là Quỳnh Trang, Thạc sĩ Tâm lý học lâm sàng, chuyên ngành Tâm lý học lâm sàng Trẻ em và Vị thành niên, đồng thời có nền tảng Cử nhân Tâm lý học, chuyên ngành Tâm lý học Tham vấn. Trong 3 năm làm việc trong lĩnh vực tâm lý, mình có cơ hội đồng hành cùng nhiều thân chủ đang trải qua căng thẳng, lo âu, trầm cảm, những ảnh hưởng liên quan đến sang chấn và các khó khăn trong mối quan hệ cặp đôi. Mình đặc biệt quan tâm đến việc giúp thân chủ hiểu hơn về những gì đang diễn ra bên trong mình, thay vì chỉ cố gắng loại bỏ một triệu chứng hay giải quyết nhanh một vấn đề. Trong quá trình làm việc, mình lựa chọn cách tiếp cận dựa trên sự thấu cảm, tôn trọng và chấp nhận vô điều kiện theo tinh thần thân chủ trọng tâm. Tùy vào nhu cầu và mục tiêu của mỗi người, mình được đào tạo và ứng dụng Liệu pháp Nhận thức Hành vi (CBT), đồng thời tích hợp các kỹ thuật điều hòa cảm xúc từ Chánh niệm và Liệu pháp Chấp nhận và Cam kết (ACT). Mình tin rằng trị liệu không phải là nơi therapist đưa ra câu trả lời thay cho thân chủ, mà là một không gian đủ an toàn để thân chủ có thể chậm lại, nhìn lại và từng bước tìm ra câu trả lời phù hợp với chính mình. Có những lúc chúng ta cần một người đồng hành để hiểu điều gì đang xảy ra; có những lúc cần một người giúp mình học cách bước qua một đoạn đường khó; và cũng có lúc điều quan trọng nhất là nhận ra mình đã đủ vững vàng để tự bước tiếp.', null, 'Mình nghĩ bản thân giống như cây gậy, thân chủ có thể cần đến cây gậy để đi qua một đoạn đường dốc và trắc trở một cách vững vàng hơn, thân chủ cũng có thể dùng cây gậy để dò dẫm xem liệu con đường mình định bước có gì nguy hiểm không và đương nhiên, sẽ có đoạn đường, thân chủ không cần đến cây gậy nữa mà có thể tự đi một cách vững vàng, an toàn. Và mình ở đây, nếu bạn cần 1 chiếc gậy.', null, true),
  ('ThS. Phương An', 'An Nguyễn Như Phương', 'Xin chào, tôi là Phương An, Thạc sĩ Tâm lý học Lâm sàng và Sức khỏe Tâm thần tại University of Sussex, Vương quốc Anh, và Cử nhân Tâm lý học tại Trường Đại học Sư phạm Hà Nội. Tôi có 4 năm kinh nghiệm trong lĩnh vực tâm lý học trường học, tham vấn và hỗ trợ sức khỏe tinh thần, với cơ hội đồng hành cùng trẻ em, thanh thiếu niên, người trưởng thành và gia đình trong nhiều bối cảnh khác nhau.

Trong công việc, tôi đặc biệt quan tâm đến những khó khăn liên quan đến lo âu, căng thẳng, điều chỉnh cảm xúc, lòng tự trọng, các mối quan hệ, học tập và quá trình thích nghi với những thay đổi trong cuộc sống. Bên cạnh việc đồng hành trực tiếp cùng thân chủ, tôi cũng hỗ trợ cha mẹ hiểu hơn về cảm xúc và hành vi của con, từ đó tìm ra những cách giao tiếp và đồng hành phù hợp hơn. Kinh nghiệm trong môi trường học đường giúp tôi nhìn nhận những khó khăn tâm lý trong mối liên hệ với nhiều yếu tố xung quanh một người, bao gồm gia đình, nhà trường và các mối quan hệ.

Trong tham vấn và trị liệu, tôi sử dụng Liệu pháp Nhận thức – Hành vi (CBT), Liệu pháp Chấp nhận và Cam kết (ACT), chánh niệm và một số kỹ thuật từ DBT. Tôi linh hoạt kết hợp các phương pháp dựa trên nhu cầu, mục tiêu và nhịp độ của từng thân chủ. Tôi tin rằng không có một công thức chung cho hành trình của mỗi người; điều quan trọng là cùng tìm ra một cách tiếp cận phù hợp và xây dựng một không gian đủ an toàn để thân chủ có thể thành thật với chính mình.

Tôi tin rằng mỗi người, dù là một đứa trẻ đang học cách gọi tên cảm xúc, một người trẻ đang loay hoay với những lựa chọn của mình, hay một người trưởng thành đang tìm lại hướng đi, đều xứng đáng được lắng nghe và thấu hiểu. Với tôi, trị liệu không phải là việc đưa ra câu trả lời thay bạn, mà là cùng bạn xây dựng một mối quan hệ đủ an toàn để bạn có thể là chính mình, hiểu bản thân sâu sắc hơn và từng bước tìm ra cách sống phù hợp với những điều thực sự có ý nghĩa với mình.', null, null, null, true),
  ('ThS. Gia Bảo', 'Trần Gia Bảo', 'Xin chào, tôi là Gia Bảo, Thạc sĩ Tâm lý học tại Trường Đại học Giáo dục, Đại học Quốc gia Hà Nội, sau khi tốt nghiệp Cử nhân Tâm lý học tại Trường Đại học Sư phạm Hà Nội. Tôi có 4 năm kinh nghiệm trong lĩnh vực can thiệp các khó khăn và rối loạn hướng nội, đặc biệt là trầm cảm, lo âu và rối loạn nhân cách ranh giới. Bên cạnh thực hành, tôi cũng tham gia giảng dạy các khóa học chuyên môn về tâm lý học.

Trong quá trình làm việc, tôi sử dụng Liệu pháp Nhận thức Hành vi (CBT) làm phương pháp chính, kết hợp một số kỹ thuật từ Liệu pháp Hành vi Biện chứng (DBT) tùy theo nhu cầu và mục tiêu của từng thân chủ. Tôi tin rằng trị liệu không chỉ nhằm giảm bớt những triệu chứng đang gây khó khăn, mà còn giúp thân chủ hiểu mình hơn và từng bước có khả năng tự ứng phó với những thử thách trong cuộc sống.

Tôi tin rằng mục tiêu sâu xa nhất của trị liệu là giúp thân chủ trở thành chuyên gia tâm lý của chính mình – người có thể nhận biết, thấu hiểu và tự mình ứng phó với những khó khăn trong cuộc sống.

Vì vậy, tôi mong muốn tạo ra một không gian an toàn, nơi bạn có thể được lắng nghe và chia sẻ mà không sợ bị phán xét. Tôi sẽ cùng bạn khám phá những điều đang diễn ra, nhận diện nguồn lực của bản thân và từng bước tìm ra cách phù hợp để chăm sóc sức khỏe tinh thần của mình.', null, null, null, true),
  ('ThS. Kim Ngân', 'Nguyễn Thị Kim Ngân', 'Xin chào, tôi là Kim Ngân, Thạc sĩ Tâm lý học theo định hướng ứng dụng tại Trường Đại học Khoa học Xã hội và Nhân văn, Đại học Quốc gia Hà Nội, với 7 năm học tập và thực hành trong lĩnh vực sức khỏe tâm thần. Trong quá trình làm việc, tôi có cơ hội đồng hành cùng những người đang trải qua sang chấn, những trải nghiệm khó khăn thời thơ ấu và các vấn đề liên quan đến rối loạn cảm xúc như lo âu, trầm cảm, lưỡng cực, cũng như những khó khăn về giá trị bản thân, ranh giới, các mối quan hệ và sức khỏe sinh sản.

Tôi đặc biệt quan tâm đến cách những trải nghiệm trong quá khứ có thể để lại dấu ấn trong cách mỗi người nhìn nhận bản thân, cảm nhận cảm xúc và xây dựng mối quan hệ với những người xung quanh. Vì vậy, trong quá trình trị liệu, tôi mong muốn cùng thân chủ từ từ khám phá câu chuyện của chính mình, hiểu hơn về những điều đã hình thành nên con người hiện tại và tìm lại những nguồn lực bên trong để có thể sống theo cách phù hợp hơn với bản thân.

Trong thực hành, tôi sử dụng linh hoạt Liệu pháp Nhận thức Hành vi (CBT), Chánh niệm (Mindfulness) và Liệu pháp Hành vi Biện chứng (DBT), tùy thuộc vào nhu cầu, mục tiêu và nhịp độ của từng thân chủ. Với tôi, trị liệu không phải là một quá trình buộc chúng ta phải trở thành một phiên bản hoàn toàn khác, mà là cơ hội để hiểu mình sâu sắc hơn, học cách ở cùng những phần dễ tổn thương và từng bước xây dựng khả năng chăm sóc chính mình.

Tôi tin rằng mỗi người đều có khả năng hồi phục, ngay cả khi đang ở trong những giai đoạn khó khăn nhất. Tôi mong muốn tạo ra một không gian an toàn và đủ dịu dàng để bạn có thể được lắng nghe, được thấu hiểu và có thời gian phát triển theo nhịp độ của riêng mình. Có thể hành trình ấy bắt đầu từ một đêm tối, nhưng tôi tin rằng ở đâu đó bên trong mỗi người vẫn luôn có một hạt mầm đang chờ được chăm sóc để một ngày có thể nở hoa.', null, 'Nảy mầm trong đêm tối và nở hoa dưới ánh mặt trời.', null, true)
  ) as v(therapist_name, full_name, bio_vi, bio_en, quote_vi, quote_en, is_published)
  left join therapists t on t.name = v.therapist_name
  group by v.therapist_name
)
select
  coalesce(sum(match_count), 0)::bigint,
  count(*) filter (where match_count <> 1)::bigint
into mapped_profile_count, invalid_profile_match_count
from profile_match_counts;

  if mapped_profile_count <> 9
    or invalid_profile_match_count > 0
  then
    raise exception
      'Expected exactly 9 uniquely matched therapist profiles; found % mapping rows and % invalid name matches',
      mapped_profile_count,
      invalid_profile_match_count;
  end if;
end
$$;

insert into therapist_profiles (
  therapist_id, full_name, bio_vi, bio_en,
  quote_vi, quote_en, is_published, updated_at
)
select
  t.id, v.full_name, v.bio_vi, v.bio_en,
  v.quote_vi, v.quote_en, v.is_published, now()
from (values
  ('ThS. Đức Minh', 'Nguyễn Đức Minh', 'Xin chào, tôi là Đức Minh, Thạc sĩ Tâm lý Liệu pháp và Tham vấn Tâm lý tại Western Sydney University, tốt nghiệp với thành tích Distinction và Dean’s Merit List Award. Tôi đồng thời là Nhà Tham vấn Tâm lý Thực hành được chứng nhận bởi PACFA – Liên đoàn Trị liệu và Tham vấn Tâm lý Úc, với hơn 750 giờ thực hành lâm sàng trong các môi trường tham vấn học đường và hỗ trợ tâm lý cho người lao động tại Sydney, Úc. Trong quá trình làm việc, tôi có cơ hội đồng hành cùng thanh thiếu niên và người trưởng thành đang trải qua lo âu, trầm cảm, căng thẳng, sang chấn, những tổn thương gắn bó và các khó khăn trong mối quan hệ.

Tôi đặc biệt quan tâm đến những tổn thương có thể hình thành từ các mối quan hệ quan trọng trong cuộc đời và cách chúng tiếp tục ảnh hưởng đến cách một người nhìn nhận bản thân, cảm nhận cảm xúc và kết nối với những người xung quanh. Với tôi, việc hiểu một khó khăn không chỉ nằm ở việc nhìn vào điều đang xảy ra ở hiện tại, mà còn cần đặt nó trong câu chuyện, những mối quan hệ và bối cảnh sống của mỗi người. Vì vậy, tôi sử dụng nền tảng Nhân vị Trọng tâm (Person-Centred Therapy), Hệ thống Gia đình (Family Systems Therapy), Phỏng vấn tạo Động lực (Motivational Interviewing), Liệu pháp Tập trung vào Cảm xúc (Emotionally Focused Therapy) để cùng thân chủ khám phá những nhu cầu, cảm xúc và khuôn mẫu đang ảnh hưởng đến cuộc sống của mình.

Tôi cũng đồng hành cùng các cặp đôi trong những giai đoạn nhiều thay đổi, khi khác biệt về kỳ vọng, tài chính, sự nghiệp, nuôi dạy con cái hay trách nhiệm với gia đình bắt đầu tạo ra khoảng cách giữa hai người. Tôi tin rằng mâu thuẫn không nhất thiết là dấu hiệu một mối quan hệ đã thất bại; đôi khi đó là tín hiệu cho thấy cả hai đang có những nhu cầu chưa được nhìn thấy và lắng nghe.

Với tôi, trị liệu tâm lý trước hết cần là một không gian an toàn, bảo mật và không phán xét, nơi bạn có thể thành thật với những điều khó nói, được lắng nghe và tôn trọng. Từ đó, chúng ta cùng tìm ra cách để bạn hiểu mình sâu sắc hơn, xây dựng những kết nối lành mạnh hơn và từng bước sống một cuộc đời phù hợp với điều mình thực sự coi trọng.', null, null, null, true),
  ('ThS. Thu Thuỷ', 'Nguyễn Thu Thủy', 'Xin chào, tôi là Thu Thuỷ, tốt nghiệp Thạc sĩ Tham vấn tâm lý tại Assumption University, Thái Lan và bắt đầu thực hành tham vấn từ năm 2023. Tôi cũng là thành viên của hiệp hội TCPA (Thailand Counseling Psychology Association). Trong quá trình làm việc, tôi có cơ hội đồng hành cùng các thân chủ trong tham vấn cá nhân, cặp đôi và nhóm, đặc biệt trong những khó khăn liên quan đến mối quan hệ, sang chấn thời thơ ấu, kiểu gắn bó và căng thẳng.

Đối với các bạn du học sinh hay Việt Kiều thì tôi càng hiểu rõ hơn vì bản thân đã từng trải qua và có những trải nghiệm để có thể đồng điệu với các bạn. Đối với các bạn sắp cưới, đã cưới và có con thì tôi lại càng hiểu hơn khi có thể đồng hành cùng bạn đi qua những cột mốc lớn trong cuộc đời.

Ngoài ra, tôi từng tham gia hỗ trợ trị liệu nhóm tại Horizon Rehab, với các chương trình như phòng ngừa tái sử dụng chất và trị liệu nhóm dựa trên nghệ thuật dành cho những người gặp khó khăn về sử dụng chất và sức khỏe tâm thần. Đồng thời, tôi đã đồng hành cùng Wabi Therapy từ những ngày đầu tiên và tiếp tục thực hành tại đây cho đến hiện tại.

Trong tham vấn, tôi kết hợp linh hoạt Psychodynamic, Gestalt, Liệu pháp Nhận thức Hành vi (CBT), Liệu pháp Hành vi Biện chứng (DBT), trị liệu dựa trên nghệ thuật và các phương pháp tiếp cận khác. Tôi không tin rằng có một phương pháp duy nhất phù hợp với tất cả mọi người vì mỗi thân chủ đều có một câu chuyện, một nhịp độ và những nhu cầu rất riêng. Vì vậy, điều tôi quan tâm là cùng bạn tìm ra cách tiếp cận phù hợp nhất với hành trình của mình.

Con đường đến với tâm lý của tôi cũng bắt đầu từ sự tò mò. Trước khi được đào tạo bài bản về Tâm lý, tôi từng tìm hiểu về Reiki (và đạt level I), Tarot, Oracle Cards (từng ứng dụng vào trong tham vấn với vẽ) và những phương pháp chữa lành tự nhiên. Những trải nghiệm đó khơi lên trong tôi nhiều câu hỏi về con người, cảm xúc và quá trình chữa lành để rồi đưa tôi đến với tâm lý học một cách khoa học và chuyên nghiệp hơn.

Với tôi, tham vấn không phải là nơi bạn được “sửa chữa” mà là một không gian để bạn có thể chậm lại, được lắng nghe và nhìn lại chính mình với sự tò mò thay vì phán xét. Chúng ta cùng nói chuyện, thảo luận về một chủ đề nào đó. Không cần gấp gáp, chầm chậm và từ tốn khai mở nút thắt trong lòng. Từ đó, bạn có thể hiểu mình hơn, nhận ra những điều mình thực sự cần và có thêm lựa chọn cho cách mình muốn sống, yêu thương và kết nối với người khác.', null, null, null, true),
  ('ThS. Ngọc Mai', 'Nguyễn Ngọc Mai', 'Xin chào, tôi là Ngọc Mai, Thạc sĩ Tâm lý học chuyên ngành Tâm lý lâm sàng và Cử nhân Tâm lý học chuyên ngành Tham vấn tâm lý tại Trường Đại học Khoa học Xã hội và Nhân văn, Đại học Quốc gia Hà Nội. Tôi bắt đầu thực hành tham vấn và trị liệu tâm lý từ năm 2020, và trong quá trình làm việc, tôi chủ yếu đồng hành cùng những người trẻ từ 18–35 tuổi đang tìm cách hiểu mình hơn, điều chỉnh cảm xúc, xây dựng những mối quan hệ lành mạnh và tìm kiếm một hướng đi phù hợp cho cuộc sống.

Tôi có kinh nghiệm đồng hành với những khó khăn liên quan đến tổn thương và trải nghiệm thời thơ ấu, căng thẳng, lo âu, trầm cảm, lòng tự trọng, tự chỉ trích, khủng hoảng và cảm giác mất phương hướng. Bên cạnh đó, tôi cũng làm việc với những vấn đề về gắn bó, các khuôn mẫu lặp lại trong tình yêu và các mối quan hệ gia đình, cũng như những áp lực trong học tập, công việc, định hướng nghề nghiệp và khủng hoảng sự nghiệp. Trong quá trình trị liệu, tôi linh hoạt kết hợp Trị liệu Nhân vị trọng tâm, Trị liệu Nhận thức Hành vi (CBT), Trị liệu Nhận thức Hành vi kết hợp Chánh niệm (MiCBT) và Hệ thống Gia đình Nội tâm (IFS), tùy thuộc vào nhu cầu, mục tiêu và nhịp độ riêng của từng thân chủ.

Tôi tin rằng bạn là người hiểu rõ nhất cuộc sống của mình và là người quyết định mình muốn đi về đâu. Nếu hành trình ấy giống như việc đi qua một đêm tối, tôi muốn mình giống như một chiếc đèn pin – không đi thay bạn, không quyết định con đường thay bạn, mà giúp bạn nhìn rõ hơn những gì đang ở phía trước.

Với tôi, tìm đến một nhà tâm lý không có nghĩa là bạn yếu đuối hay không thể tự giải quyết vấn đề. Đôi khi, đó chính là một cách để bạn dũng cảm đối diện với những điều mình đã cố gắng chịu đựng một mình quá lâu. Trị liệu không phải là hành trình để trở thành một con người hoàn toàn khác, mà là quá trình hiểu mình hơn, học cách chấp nhận cả những phần dễ tổn thương, tìm lại những nguồn lực vốn có và từng bước xây dựng một cuộc sống phù hợp hơn với chính mình. Tôi hy vọng quá trình đồng hành của chúng ta sẽ giúp bạn không chỉ vượt qua một giai đoạn khó khăn, mà còn dần học được cách trở thành người có thể lắng nghe, thấu hiểu và đồng hành cùng chính mình.', null, null, null, true),
  ('ThS. Minh Châu', 'Minh Châu', 'Xin chào, tôi là Minh Châu, Thạc sĩ Tâm lý học tại Trường Đại học Sư phạm Thành phố Hồ Chí Minh, với 7 năm kinh nghiệm thực hành trong lĩnh vực chăm sóc sức khỏe tâm thần. Trong quá trình làm việc, tôi có cơ hội đồng hành cùng nhiều thân chủ đang trải qua những khó khăn về lo âu, trầm cảm, đau buồn và mất mát, những vấn đề trong mối quan hệ gắn bó cũng như những ảnh hưởng còn kéo dài từ các trải nghiệm bất lợi thời thơ ấu.

Tôi đặc biệt quan tâm đến cách những trải nghiệm trong quá khứ có thể tiếp tục hiện diện trong đời sống hiện tại của mỗi người – qua cách chúng ta nhìn nhận bản thân, cảm nhận và điều hòa cảm xúc, xây dựng các mối quan hệ hay phản ứng trước những tình huống quen thuộc. Vì vậy, trong quá trình đồng hành, tôi không chỉ quan tâm đến điều đang khiến bạn khó khăn ở hiện tại, mà còn cùng bạn từ từ khám phá những câu chuyện, nhu cầu và trải nghiệm phía sau những điều ấy.

Về phương pháp, tôi thực hành theo hướng tích hợp, lấy nền tảng từ Phân tâm học (Psychoanalytic) và linh hoạt kết hợp các góc nhìn từ Tâm lý học Adler (Adlerian), thực hành Chú tâm (Mindfulness), sử dụng nghệ thuật như công cụ biểu đạt (art-based methods). Tôi tin rằng mỗi người có một câu chuyện riêng, vì vậy trị liệu cũng cần được điều chỉnh theo nhu cầu, khả năng và nhịp độ của từng thân chủ thay vì áp dụng một công thức giống nhau cho tất cả.

Với tôi, tham vấn tâm lý trước hết là một mối quan hệ an toàn, là không gian lắng nghe thấu đáo và không phán xét để bạn chậm lại, gọi tên và khám phá bất kỳ khía cạnh nào liên quan nhất đến sự an lành của mình — kể cả những bối rối hay nỗi đau sâu kín chưa thể gọi tên. Tôi mong muốn đồng hành cùng bạn để từng bước thấu hiểu, chấp nhận chính bản thân và sẵn sàng kết nối lành mạnh với cuộc sống.', null, null, null, true),
  ('ThS. Ly Đinh', 'Đinh Y Ly', 'Xin chào.

Tôi là Ly, là một thạc sĩ tâm lí (lâm sàng) được đào tạo từ trường ĐH KHXH&NV, ĐHQG Hà Nội với hơn 6 năm kinh nghiệm làm việc trong lĩnh vực tâm lí, bao gồm cung cấp dịch vụ đánh giá, tham vấn và trị liệu tâm lí cho các khách hàng cá nhân.

Từ những trải nghiệm cá nhân kết hợp với quá trình học tập, nghiên cứu và thực hành, tôi đã xác định và phát triển chuyên môn theo định hướng làm việc với các thân chủ là người trưởng thành mang những nỗi đau từ các trải nghiệm bất lợi, tổn thương, sang chấn thời thơ ấu. Các tổn thương đó có thể biểu hiện thành những rối loạn như trầm cảm, lo âu, cũng có thể ảnh hưởng đến lòng tự trọng, cách mỗi người nhìn nhận và đánh giá bản thân, lối hành xử và tương tác trong các mối quan hệ với người khác. Vì vậy, đây không phải một quá trình dễ dàng và nhanh chóng, nhưng tôi tin rằng mình đủ kiên nhẫn, kiến thức và trải nghiệm để đồng hành cùng bạn đi đến cuối hành trình khám phá và tự hàn gắn này.

Trong quá trình làm việc, tôi sử dụng kết hợp liệu pháp CBT với các triết lí và kĩ thuật về thân chủ trọng tâm, chánh niệm, chấp nhận và cam kết (ACT). Tuy vậy, đối với tôi, trị liệu tâm lí không chỉ là thực hành các liệu pháp hay kĩ thuật, mà đó là quá trình một người mở rộng vùng trải nghiệm của mình, thêm vào đó các trải nghiệm tích cực như được chấp nhận vô điều kiện, được lắng nghe, được nhìn thấy, được sự an toàn, được thử, được sai, được thử lại... Từ đó, bạn có thể dấn thân vào cuộc sống và các mối quan hệ, nhìn nhận các giá trị của bản thân, lấy lại sự tự chủ, tự do, niềm tin vào chính mình để hướng tới một cuộc sống bình an, độc lập.

Ngoài ra, tôi cũng đồng hành và hỗ trợ những người đang trải qua đau buồn và mất mát – dù đó là sự ra đi của người thân, thú cưng, chia tay mối quan hệ hay việc phải đối diện với bệnh tật và những thay đổi lớn trong cuộc sống. Đây đều là những trải nghiệm không dễ dàng, và bạn hoàn toàn có quyền lựa chọn không phải trải qua chúng một mình. Các phiên làm việc đều là không gian an toàn để bạn có thể từng bước nhìn nhận và xử lý những cảm xúc bạn đang trải qua, giải tỏa những điều còn dồn nén, thích nghi và dần tìm lại sự cân bằng trong cuộc sống.

Thực hành của tôi đều dựa trên các nguyên tắc đạo đức nghề nghiệp, sự tôn trọng và tin tưởng đối với mỗi thân chủ của mình. Mọi hoạt động hỗ trợ đều hướng đến lợi ích, nhu cầu và sự an toàn của chính bạn.', null, null, null, true),
  ('ThS. Quỳnh Trang', 'Ngọ Quỳnh Trang', 'Mình là Quỳnh Trang, Thạc sĩ Tâm lý học lâm sàng, chuyên ngành Tâm lý học lâm sàng Trẻ em và Vị thành niên, đồng thời có nền tảng Cử nhân Tâm lý học, chuyên ngành Tâm lý học Tham vấn. Trong 3 năm làm việc trong lĩnh vực tâm lý, mình có cơ hội đồng hành cùng nhiều thân chủ đang trải qua căng thẳng, lo âu, trầm cảm, những ảnh hưởng liên quan đến sang chấn và các khó khăn trong mối quan hệ cặp đôi. Mình đặc biệt quan tâm đến việc giúp thân chủ hiểu hơn về những gì đang diễn ra bên trong mình, thay vì chỉ cố gắng loại bỏ một triệu chứng hay giải quyết nhanh một vấn đề. Trong quá trình làm việc, mình lựa chọn cách tiếp cận dựa trên sự thấu cảm, tôn trọng và chấp nhận vô điều kiện theo tinh thần thân chủ trọng tâm. Tùy vào nhu cầu và mục tiêu của mỗi người, mình được đào tạo và ứng dụng Liệu pháp Nhận thức Hành vi (CBT), đồng thời tích hợp các kỹ thuật điều hòa cảm xúc từ Chánh niệm và Liệu pháp Chấp nhận và Cam kết (ACT). Mình tin rằng trị liệu không phải là nơi therapist đưa ra câu trả lời thay cho thân chủ, mà là một không gian đủ an toàn để thân chủ có thể chậm lại, nhìn lại và từng bước tìm ra câu trả lời phù hợp với chính mình. Có những lúc chúng ta cần một người đồng hành để hiểu điều gì đang xảy ra; có những lúc cần một người giúp mình học cách bước qua một đoạn đường khó; và cũng có lúc điều quan trọng nhất là nhận ra mình đã đủ vững vàng để tự bước tiếp.', null, 'Mình nghĩ bản thân giống như cây gậy, thân chủ có thể cần đến cây gậy để đi qua một đoạn đường dốc và trắc trở một cách vững vàng hơn, thân chủ cũng có thể dùng cây gậy để dò dẫm xem liệu con đường mình định bước có gì nguy hiểm không và đương nhiên, sẽ có đoạn đường, thân chủ không cần đến cây gậy nữa mà có thể tự đi một cách vững vàng, an toàn. Và mình ở đây, nếu bạn cần 1 chiếc gậy.', null, true),
  ('ThS. Phương An', 'An Nguyễn Như Phương', 'Xin chào, tôi là Phương An, Thạc sĩ Tâm lý học Lâm sàng và Sức khỏe Tâm thần tại University of Sussex, Vương quốc Anh, và Cử nhân Tâm lý học tại Trường Đại học Sư phạm Hà Nội. Tôi có 4 năm kinh nghiệm trong lĩnh vực tâm lý học trường học, tham vấn và hỗ trợ sức khỏe tinh thần, với cơ hội đồng hành cùng trẻ em, thanh thiếu niên, người trưởng thành và gia đình trong nhiều bối cảnh khác nhau.

Trong công việc, tôi đặc biệt quan tâm đến những khó khăn liên quan đến lo âu, căng thẳng, điều chỉnh cảm xúc, lòng tự trọng, các mối quan hệ, học tập và quá trình thích nghi với những thay đổi trong cuộc sống. Bên cạnh việc đồng hành trực tiếp cùng thân chủ, tôi cũng hỗ trợ cha mẹ hiểu hơn về cảm xúc và hành vi của con, từ đó tìm ra những cách giao tiếp và đồng hành phù hợp hơn. Kinh nghiệm trong môi trường học đường giúp tôi nhìn nhận những khó khăn tâm lý trong mối liên hệ với nhiều yếu tố xung quanh một người, bao gồm gia đình, nhà trường và các mối quan hệ.

Trong tham vấn và trị liệu, tôi sử dụng Liệu pháp Nhận thức – Hành vi (CBT), Liệu pháp Chấp nhận và Cam kết (ACT), chánh niệm và một số kỹ thuật từ DBT. Tôi linh hoạt kết hợp các phương pháp dựa trên nhu cầu, mục tiêu và nhịp độ của từng thân chủ. Tôi tin rằng không có một công thức chung cho hành trình của mỗi người; điều quan trọng là cùng tìm ra một cách tiếp cận phù hợp và xây dựng một không gian đủ an toàn để thân chủ có thể thành thật với chính mình.

Tôi tin rằng mỗi người, dù là một đứa trẻ đang học cách gọi tên cảm xúc, một người trẻ đang loay hoay với những lựa chọn của mình, hay một người trưởng thành đang tìm lại hướng đi, đều xứng đáng được lắng nghe và thấu hiểu. Với tôi, trị liệu không phải là việc đưa ra câu trả lời thay bạn, mà là cùng bạn xây dựng một mối quan hệ đủ an toàn để bạn có thể là chính mình, hiểu bản thân sâu sắc hơn và từng bước tìm ra cách sống phù hợp với những điều thực sự có ý nghĩa với mình.', null, null, null, true),
  ('ThS. Gia Bảo', 'Trần Gia Bảo', 'Xin chào, tôi là Gia Bảo, Thạc sĩ Tâm lý học tại Trường Đại học Giáo dục, Đại học Quốc gia Hà Nội, sau khi tốt nghiệp Cử nhân Tâm lý học tại Trường Đại học Sư phạm Hà Nội. Tôi có 4 năm kinh nghiệm trong lĩnh vực can thiệp các khó khăn và rối loạn hướng nội, đặc biệt là trầm cảm, lo âu và rối loạn nhân cách ranh giới. Bên cạnh thực hành, tôi cũng tham gia giảng dạy các khóa học chuyên môn về tâm lý học.

Trong quá trình làm việc, tôi sử dụng Liệu pháp Nhận thức Hành vi (CBT) làm phương pháp chính, kết hợp một số kỹ thuật từ Liệu pháp Hành vi Biện chứng (DBT) tùy theo nhu cầu và mục tiêu của từng thân chủ. Tôi tin rằng trị liệu không chỉ nhằm giảm bớt những triệu chứng đang gây khó khăn, mà còn giúp thân chủ hiểu mình hơn và từng bước có khả năng tự ứng phó với những thử thách trong cuộc sống.

Tôi tin rằng mục tiêu sâu xa nhất của trị liệu là giúp thân chủ trở thành chuyên gia tâm lý của chính mình – người có thể nhận biết, thấu hiểu và tự mình ứng phó với những khó khăn trong cuộc sống.

Vì vậy, tôi mong muốn tạo ra một không gian an toàn, nơi bạn có thể được lắng nghe và chia sẻ mà không sợ bị phán xét. Tôi sẽ cùng bạn khám phá những điều đang diễn ra, nhận diện nguồn lực của bản thân và từng bước tìm ra cách phù hợp để chăm sóc sức khỏe tinh thần của mình.', null, null, null, true),
  ('ThS. Kim Ngân', 'Nguyễn Thị Kim Ngân', 'Xin chào, tôi là Kim Ngân, Thạc sĩ Tâm lý học theo định hướng ứng dụng tại Trường Đại học Khoa học Xã hội và Nhân văn, Đại học Quốc gia Hà Nội, với 7 năm học tập và thực hành trong lĩnh vực sức khỏe tâm thần. Trong quá trình làm việc, tôi có cơ hội đồng hành cùng những người đang trải qua sang chấn, những trải nghiệm khó khăn thời thơ ấu và các vấn đề liên quan đến rối loạn cảm xúc như lo âu, trầm cảm, lưỡng cực, cũng như những khó khăn về giá trị bản thân, ranh giới, các mối quan hệ và sức khỏe sinh sản.

Tôi đặc biệt quan tâm đến cách những trải nghiệm trong quá khứ có thể để lại dấu ấn trong cách mỗi người nhìn nhận bản thân, cảm nhận cảm xúc và xây dựng mối quan hệ với những người xung quanh. Vì vậy, trong quá trình trị liệu, tôi mong muốn cùng thân chủ từ từ khám phá câu chuyện của chính mình, hiểu hơn về những điều đã hình thành nên con người hiện tại và tìm lại những nguồn lực bên trong để có thể sống theo cách phù hợp hơn với bản thân.

Trong thực hành, tôi sử dụng linh hoạt Liệu pháp Nhận thức Hành vi (CBT), Chánh niệm (Mindfulness) và Liệu pháp Hành vi Biện chứng (DBT), tùy thuộc vào nhu cầu, mục tiêu và nhịp độ của từng thân chủ. Với tôi, trị liệu không phải là một quá trình buộc chúng ta phải trở thành một phiên bản hoàn toàn khác, mà là cơ hội để hiểu mình sâu sắc hơn, học cách ở cùng những phần dễ tổn thương và từng bước xây dựng khả năng chăm sóc chính mình.

Tôi tin rằng mỗi người đều có khả năng hồi phục, ngay cả khi đang ở trong những giai đoạn khó khăn nhất. Tôi mong muốn tạo ra một không gian an toàn và đủ dịu dàng để bạn có thể được lắng nghe, được thấu hiểu và có thời gian phát triển theo nhịp độ của riêng mình. Có thể hành trình ấy bắt đầu từ một đêm tối, nhưng tôi tin rằng ở đâu đó bên trong mỗi người vẫn luôn có một hạt mầm đang chờ được chăm sóc để một ngày có thể nở hoa.', null, 'Nảy mầm trong đêm tối và nở hoa dưới ánh mặt trời.', null, true)
) as v(therapist_name, full_name, bio_vi, bio_en, quote_vi, quote_en, is_published)
join therapists t on t.name = v.therapist_name
on conflict (therapist_id) do update set
  full_name = excluded.full_name,
  bio_vi = excluded.bio_vi,
  bio_en = excluded.bio_en,
  quote_vi = excluded.quote_vi,
  quote_en = excluded.quote_en,
  is_published = excluded.is_published,
  updated_at = now();
-- END GENERATED THERAPIST PROFILES
