#!/usr/bin/env node
// Regenerates supabase/migrations/0003_faq.sql from data/faq.json.
//
//   node scripts/extract-xlsx.mjs <sheet.xlsx>   # xlsx → data/*.json
//   node scripts/faq-sql.mjs                     # data/faq.json → migration
//
// The seeded `answer` is the revised text when the team wrote one (column
// "Sửa lại"), otherwise the original. `review_note` carries their comment so the
// editorial trail survives into the database.

import fs from 'node:fs'
import path from 'node:path'

const faq = JSON.parse(fs.readFileSync(path.join(process.cwd(), 'data/faq.json'), 'utf8'))
const q = (s) => (s == null ? 'null' : `'${String(s).replace(/'/g, "''")}'`)

const rows = faq.entries.map(
  (e) =>
    `  (${e.id}, ${q(e.topic)}, ${q(e.question)}, ${q(e.answer)}, ${q(e.priority)}, ${q(e.channels.join(' · '))}, ${e.hasRevision}, ${q(e.reviewNote)})`
)

const revised = faq.entries.filter((e) => e.hasRevision).length

const sql = `-- FAQ bank — the chat assistant's grounding corpus.
--
-- GENERATED by scripts/faq-sql.mjs from data/faq.json. Do not hand-edit: rerun
-- the extractor when the team sends a new spreadsheet. Day-to-day wording fixes
-- are fine to make in the Supabase Table Editor, but a regeneration overwrites
-- them, so push those back into the spreadsheet too.
--
-- Source: ${faq.source} (sheet "FAQ") — ${faq.count} questions, ${revised} of them
-- carrying a rewritten answer from the "Sửa lại" column. Those rewrites are what
-- gets seeded; \`is_revised\` marks them and \`review_note\` keeps the editor's comment.
--
-- Vietnamese only. English questions are answered from these same rows, with the
-- model translating at answer time — see the system prompt in app/api/chat/route.ts.

create table if not exists faq (
  id bigint generated always as identity primary key,
  sort_order int not null,
  topic text not null,
  question text not null,
  answer text not null,
  priority text not null,
  channels text not null,
  is_revised boolean not null default false,
  review_note text
);

alter table faq enable row level security;

-- Read server-side with the anon key, same as the other content tables.
drop policy if exists "public read faq" on faq;
create policy "public read faq" on faq for select using (true);

delete from faq;

insert into faq (sort_order, topic, question, answer, priority, channels, is_revised, review_note) values
${rows.join(',\n')};
`

const out = path.join(process.cwd(), 'supabase/migrations/0003_faq.sql')
fs.writeFileSync(out, sql)
console.log(`wrote ${path.relative(process.cwd(), out)} — ${rows.length} rows, ${revised} using the revised answer`)
