-- FAQ bank — the chat assistant's grounding corpus.
--
-- GENERATED by scripts/faq-sql.mjs from data/faq.json. Do not hand-edit: rerun
-- the extractor when the team sends a new spreadsheet. Day-to-day wording fixes
-- are fine to make in the Supabase Table Editor, but a regeneration overwrites
-- them, so push those back into the spreadsheet too.
--
-- Source: 73716d86-wabifaq50.xlsx (sheet "FAQ") — 44 questions, 15 of them
-- carrying a rewritten answer from the "Sửa lại" column. Those rewrites are what
-- gets seeded; `is_revised` marks them and `review_note` keeps the editor's comment.
--
-- Vietnamese only. English questions are answered from these same rows, with the
-- model translating at answer time — see the system prompt in app/api/chat/route.ts.

create table if not exists faq (
  id bigint generated always as identity primary key,
  sort_order int not null,
  topic text not null,
  question text not null,
  answer text not null,
  priority text not null,
  channels text not null,
  is_revised boolean not null default false,
  review_note text
);

alter table faq enable row level security;

-- Read server-side with the anon key, same as the other content tables.
drop policy if exists "public read faq" on faq;
create policy "public read faq" on faq for select using (true);

delete from faq;

insert into faq (sort_order, topic, question, answer, priority, channels, is_revised, review_note) values
  (1, 'Bắt đầu', 'Tham vấn tâm lý là gì?', '1/ Tham vấn tâm lý là quá trình trò chuyện giữa bạn và chuyên gia nhằm làm rõ, tháo gỡ những khó khăn hoặc khúc mắc cụ thể đang diễn ra trong cuộc sống hiện tại.
Tham vấn tâm lý sẽ giúp bạn:
- Định hình vấn đề: Nhìn nhận bức tranh toàn cảnh về khó khăn bạn đang gặp phải một cách khách quan.
- Tìm kiếm giải pháp: Xác định mục tiêu, khai phá tiềm năng bản thân và đưa ra các quyết định sáng suốt.
- Rèn luyện kỹ năng: Trang bị các kỹ năng thực tế như quản lý cảm xúc, ứng phó với căng thẳng, cải thiện giao tiếp hoặc giải quyết mâu thuẫn.
Thông tin dịch vụ:
Vấn đề phù hợp: Căng thẳng công việc/học tập, áp lực thi cử, mâu thuẫn quan hệ (bạn bè, đồng nghiệp, người yêu), định hướng bản thân, khủng hoảng tuổi trưởng thành, khám phá xu hướng tính dục...
Thời lượng: thường ngắn hạn (từ 1 đến vài buổi tùy nhu cầu).
Hình thức: tham vấn cá nhân, cặp đôi hoặc gia đình (trực tiếp hoặc online).

2/ Trị liệu tâm lý là quá trình đồng hành chuyên sâu giữa bạn và nhà trị liệu nhằm thấu hiểu, xoa dịu các tổn thương tinh thần và giải quyết các rối nhiễu tâm lý.
Khác với tham vấn ngắn hạn (thường tập trung vào giải quyết vấn đề hiện tại), trị liệu tâm lý sẽ giúp bạn:
- Khám phá gốc rễ: Kết nối các trải nghiệm trong quá khứ (trải nghiệm tuổi thơ, các biến cố) với suy nghĩ, cảm xúc và hành vi hiện tại.
- Tạo sự thay đổi bền vững: Xây dựng cơ chế ứng phó lành mạnh và nâng cao năng lực tự chữa lành trước những khó khăn trong cuộc sống.
Các vấn đề: trầm cảm, lo âu, rối loạn hoảng sợ, rối loạn căng thẳng sang chấn, rối loạn ăn uống, các rối loạn nhân cách, căng thẳng mạn tính...
Đối tượng: Trẻ em, thanh thiếu niên, người trưởng thành và người cao tuổi.
Hình thức: Trị liệu cá nhân, cặp đôi/vợ chồng, gia đình hoặc trị liệu nhóm.
Thời lượng: Ngắn hạn (4-6 buổi) hoặc dài hạn tùy thuộc vào nhu cầu và tình trạng thực tế của bạn.', 'Cao', 'Website · Inbox', true, 'Nên tách tham vấn và trị liệu riêng; không dùng từ liên quan tới bệnh lí như "điều trị"; thống nhất sử dụng "sức khỏe tâm thần" thay cho "sức khỏe tinh thần"'),
  (2, 'Bắt đầu', 'Đánh giá tâm lý là gì? Khác gì tham vấn/trị liệu tâm lý?', 'Đánh giá tâm lý là quá trình thu thập và phân tích thông tin một cách toàn diện nhằm xác định rõ tình trạng sức khỏe tâm thần, đặc điểm tâm lý, tính cách hoặc năng lực trí tuệ của một cá nhân.
Quá trình đánh giá thường bao gồm:
- Phỏng vấn lâm sàng: Trao đổi trực tiếp về lịch sử cá nhân, các mối bận tâm và biểu hiện hiện tại.
- Sử dụng trắc nghiệm/thang đo chuẩn hóa: Thực hiện các bài test tâm lý uy tín (đo lường mức độ trầm cảm, lo âu, stress, trắc nghiệm nhân cách, trí tuệ IQ/EQ, sự tập trung chú ý...).
- Quan sát & Phân tích: Ghi nhận hành vi, phản ứng và tổng hợp dữ liệu để đưa ra kết luận chuyên môn.
Thông tin dịch vụ:
- Trường hợp phù hợp: Khi bạn muốn hiểu rõ tình trạng sức khỏe tâm thần của mình; nghi ngờ có các triệu chứng rối loạn; cần hồ sơ đánh giá cho học tập/công việc; hoặc muốn định hướng lộ trình trị liệu chính xác.
- Kết quả nhận được: Báo cáo đánh giá chi tiết kèm theo khuyến nghị/định hướng chuyên môn từ nhà tâm lý.
Thời lượng: Thường diễn ra trong 1–2 buổi (bao gồm thời gian thực hiện bài test và trả kết quả/tham vấn).
Đánh giá tâm lý không phải là "dán nhãn", mà là công cụ giúp bạn thấu hiểu bản thân một cách khoa học và tìm ra giải pháp nâng cao chất lượng cuộc sống.', 'Cao', 'Website · Inbox', true, 'Sủa từ "năng lực nhận thức" thành "đặc điểm nhận thức..."'),
  (3, 'Bắt đầu', 'Mình có ''đủ nặng'' để đi therapy không?', 'Bạn không cần chờ đến khi khủng hoảng mới tìm kiếm sự hỗ trợ. Therapy không chỉ dành cho những tổn thương hay vấn đề bệnh lí nghiêm trọng, mà còn là không gian an toàn giúp bạn thấu hiểu bản thân, cải thiện các mối quan hệ hay đơn giản là trút bỏ gánh nặng tinh thần. 
Nếu bạn đang băn khoăn câu hỏi này, đó đã là dấu hiệu cho thấy tâm trí bạn đang cần một khoảng nghỉ và sự đồng hành.', 'Cao', 'Website · Social', true, 'Câu hỏi: Thêm từ "Vấn đề của mình"
Câu trả lời: sửa lại một tí về cách viết.'),
  (4, 'Bắt đầu', 'Mình chưa sẵn sàng, có sao không?', 'Hoàn toàn không sao cả. Therapy chỉ thật sự hiệu quả khi bạn cảm thấy thoải mái và sẵn sàng mở lòng, vì vậy hãy cho bản thân thời gian nhé.
Bất cứ khi nào bạn cần giải đáp thắc mắc, tìm hiểu thêm thông tin hoặc sẵn sàng đặt lịch, Wabi luôn ở đây để hỗ trợ bạn.', 'Cao', 'Inbox', true, null),
  (5, 'Bắt đầu', 'Làm sao để bắt đầu với Wabi?', 'Chỉ cần nhắn cho Wabi qua Facebook, Instagram. Bạn chia sẻ một chút về tuổi, nơi sinh sống và vấn đề đang gặp phải, admin sẽ tư vấn therapist và dịch vụ phù hợp. Sau đó bạn trả lời vài câu hỏi screening ngắn, Wabi gửi lịch qua email, bạn xác nhận là xong.', 'Cao', 'Website · Inbox', false, null),
  (6, 'Bắt đầu', 'Buổi đầu tiên sẽ diễn ra như thế nào?', 'Buổi đầu là để bạn và therapist làm quen. Bạn chia sẻ mục tiêu và kỳ vọng (nếu có); therapist sẽ trao đổi về kế hoạch can thiệp và cách tiếp cận của họ — mỗi người mỗi khác — cùng các hướng giải quyết có thể. Bạn không cần chuẩn bị gì hoàn hảo cả, chỉ cần đến đúng như bạn đang là.', 'Cao', 'Website · Inbox', false, '34'),
  (7, 'Bắt đầu', 'Mình nên chuẩn bị gì trước buổi đầu?', 'Bạn không cần phải chuẩn bị quá nhiều hay học thuộc lòng bất kỳ điều gì trước buổi gặp đầu tiên. Việc quan trọng nhất là mang theo một tâm trí cởi mở. Tuy nhiên, bạn cũng có thể chuẩn bị trước một chút để tự tin hơn:
- Liệt kê nhanh các vấn đề: phác thảo ngắn gọn những điều đang khiến bạn bận tâm, cảm xúc bạn đang trải qua hoặc lý do chính khiến bạn tìm đến therapy.
- Xác định mong muốn: suy nghĩ xem bạn hy vọng nhận được điều gì sau quá trình này (ví dụ: giảm bớt căng thẳng/lo âu, hiểu rõ bản thân, cải thiện mối quan hệ...).
- Ghi lại các thắc mắc: chuẩn bị sẵn những câu hỏi bạn muốn hỏi nhà trị liệu (về phương pháp, bảo mật, quy trình...).
- sắp xếp không gian phù hợp (khi gặp online): Chọn một góc riêng tư, yên tĩnh, chuẩn bị tai nghe và kết nối internet ổn định.
- Mang theo cuốn sổ tay để ghi chép lại những thông tin bạn thấy quan trọng
Nhớ rằng: lhông có câu trả lời nào là đúng hay sai. Bạn hoàn toàn có thể đến buổi gặp chỉ với sự mơ hồ, therapist sẽ cùng bạn làm rõ từng chút một.', 'Cao', 'Website · Inbox', true, null),
  (8, 'Dịch vụ', 'Wabi có những dịch vụ nào?', 'Wabi có 5 nhóm dịch vụ: 
(1) Tham vấn & Trị liệu tâm lý cá nhân 
(2) Đánh giá tâm lý
(3) Tham vấn cặp đôi
(4) Art Therapy
(5) Hướng nghiệp
Tất cả các dịch vụ đều có hình thức online và một số có offline tại Hà Nội và TP.HCM.', 'Cao', 'Website', true, '(1) ghi rõ là tham vấn và trị liệu tâm lí cá nhân nhen'),
  (9, 'Dịch vụ', 'Wabi hỗ trợ những vấn đề gì?', 'Wabi đồng hành và hỗ trợ bạn giải quyết đa dạng các khó khăn tâm lý, được phân nhóm cụ thể như sau:
1/ Sức khỏe tâm thần và các rối loạn tâm lý: 
- Trầm cảm, các dạng rối loạn lo âu, ám sợ xã hội, rối loạn ám ảnh cưỡng chế (OCD), rối loạn lưỡng cực, 
- Chú ý & Hành vi: ADHD, khó khăn trong quản lý cảm xúc và tập trung.
- Rối loạn nhân cách (BPD,...).
2/ Chữa lành tổn thương và khủng hoảng tâm lý: tổn thương thời thơ ấu và các trải nghiệm tiêu cực trong quá khứ; sang chấn tâm lý (PTSD/C-PTSD); đau buồn, mất mát (chia tay, mất người thân, mất mát công việc/mục tiêu).
3/ Phát triển bản thân và nhận thức nội tâm: xây dựng lòng tự trọng, sự tự tin và xác định ranh giới cá nhân; xác định phong cách gắn bó; khủng hoảng hiện sinh, mất định hướng sống, áp lực trưởng thành
4/ Mối quan hệ môi trường sống: mâu thuẫn và khó khăn trong tình yêu, đời sống hôn nhân/gia đình; áp lực công việc, học tập, kiệt sức (burnout), giao tiếp và ứng xử xã hội.
Note: Nếu vấn đề của bạn không nằm trong danh sách trên, cũng đừng ngần ngại liên hệ để chúng tôi lắng nghe và tư vấn hướng hỗ trợ phù hợp nhất.', 'Cao', 'Website · Inbox', true, 'Chia lại các nhóm nhỏ cụ thể hơn'),
  (10, 'Dịch vụ', 'Một buổi tham vấn kéo dài bao lâu?', 'Thời lượng tiêu chuẩn cho mỗi phiên đánh giá tâm lý, tham vấn/trị liệu tâm lý cá nhân là 60 phút. Với tham vấn cặp đôi, các phiên chung với cả hai người thường kéo dài 90 phút.', 'Cao', 'Website · Inbox', true, null),
  (12, 'Dịch vụ', 'Chương trình Hướng nghiệp gồm những gì?', 'Gói Cơ bản (2 buổi): bạn làm test năng lực, trò chuyện với therapist về định hướng, và nhận báo cáo cùng lời khuyên về kết quả test. Gói Chuyên sâu (3 buổi): có thêm một buổi lên kế hoạch cụ thể để thực hiện định hướng đó. Nếu trong quá trình bạn có vấn đề tâm lý liên quan (self-esteem, động lực, cảm xúc...), therapist sẽ gợi ý làm thêm buổi riêng ngoài chương trình.', 'Trung bình', 'Website · Inbox', false, '54'),
  (13, 'Dịch vụ', 'Tham vấn cặp đôi diễn ra như thế nào?', 'Buổi đầu để khám phá nhu cầu và mục đích: 30 phút riêng cho mỗi người, sau đó 30 phút cùng nhau (hoặc tách thành 2 buổi lẻ 60 phút). Bạn không cần tham gia cùng nhau ở buổi này, giúp mỗi người thoải mái hơn. Các buổi sau cả hai cùng tham gia, 90 phút/buổi. Nếu một trong hai cần tham vấn riêng, Wabi sẽ sắp xếp buổi riêng biệt.', 'Trung bình', 'Website · Inbox', false, null),
  (14, 'Dịch vụ', 'Wabi có dịch vụ bằng tiếng Anh không?', 'Có. Wabi cung cấp tham vấn/trị liệu cho cả thân chủ trong nước và nước ngoài, bằng tiếng Việt và tiếng Anh. Ngoài ra một số therapist làm việc bằng tiếng Hàn (tham vấn cặp đôi Hàn–Việt), tiếng Quan Thoại và tiếng Quảng Đông.', 'Trung bình', 'Website · Inbox', false, null),
  (15, 'Đánh giá', 'Buổi đánh giá tâm lý diễn ra thế nào?', 'Quy trình đánh giá tâm lý ở Wabi được thực hiện chỉn chu qua 3 bước cụ thể:
Bước 1: Bạn trao đổi sơ bộ về nhu cầu và/hoặc vấn đề hiện tại với chuyên viên tiếp nhận (admin của Wabi có chuyên môn về tâm lý học). Dựa trên các thông tin này, bạn sẽ nhận và hoàn thành các bài trắc nghiệm/thang đo tâm lý phù hợp trước buổi gặp chính thức với therapist.
Bước 2: Therapist sẽ làm việc trực tiếp cùng bạn để khai thác sâu hơn về vấn đề hiện tại, lịch sử hình thành khó khăn, các yếu tố tác động... từ đó đưa ra nhận định chuyên môn và định hướng can thiệp nếu cần. (Lưu ý: một số trường hợp phức tạp hoặc nhiều thông tin, có thể cần 2 buổi làm việc với therapist).
Bước 3: Sau 7–10 ngày, bạn sẽ nhận được báo cáo đánh giá tâm lý gửi qua email, bao gồm phân tích kết quả test, nhận định của nhà tâm lý và các khuyến nghị lộ trình tiếp theo.
Sau khi nhận báo cáo, nếu có câu hỏi hay thắc mắc, bạn hoàn toàn có thể liên hệ với Wabi để được giải đáp và hỗ trợ.', 'Cao', 'Website · Inbox', true, 'Chia làm 3 bước cụ thể'),
  (16, 'Đánh giá', 'Mình sẽ làm những bài test nào?', 'Tùy thuộc vào nhu cầu và mô tả vấn đề ban đầu của bạn, Wabi sẽ gợi ý các bài test chuẩn hóa phù hợp. Trong quá trình đồng hành, nhà trị liệu có thể đề xuất thêm một số công cụ đánh giá khác để có bức tranh toàn diện nhất.
Các bài test thường được sử dụng bao gồm:
- Sức khỏe tinh thần: Đo lường mức độ trầm cảm (BDI-II), lo âu (Zung/GAD-7), lưỡng cực (MDQ), sang chấn tâm lý (PCL-5)...
- Tính cách và nhận thức bản thân: Trắc nghiệm nhân cách Big Five, trắc nghiệm đa trí thông minh (Howard Gardner), Đánh giá chỉ số trí tuệ (IQ)...
- Chất lượng sống và cảm xúc: Đánh giá lòng tự trọng (Sorensen), Đo lường mức độ hạnh phúc & sức khỏe tinh thần tổng thể (Carol Ryff)...
Note: Các bài test tại Wabi chỉ đóng vai trò là công cụ hỗ trợ. Kết quả test luôn được therapist phân tích sâu và kết hợp với phỏng vấn lâm sàng để đảm bảo chính xác và khách quan.', 'Cao', 'Website · Inbox', true, 'Câu hỏi: Các bài test nào thường được sử dụng ở Wabi?'),
  (17, 'Đánh giá', 'File báo cáo PDF có bắt buộc không? Có tính phí riêng không?', 'Chi phí đánh giá tâm lý tại Wabi chủ yếu nằm ở buổi gặp trực tiếp với therapist. File tổng hợp là phần hỗ trợ thêm — như một món quà bonus therapist dành tặng, không có cơ sở nào bắt buộc phải thực hiện. Vì vậy trong buổi bạn hoàn toàn có thể đặt câu hỏi trực tiếp và ghi âm lại nếu cần.', 'Trung bình', 'Website · Inbox', false, '70'),
  (18, 'Đánh giá', 'Kết quả đánh giá có phải là chẩn đoán bệnh không?', 'Không. Nhà tâm lý đưa ra đánh giá chuyên môn dựa trên các ngưỡng lâm sàng (ví dụ: bạn có triệu chứng của rối loạn trầm cảm và đã đạt ngưỡng lâm sàng 6–7 triệu chứng), nhưng việc đưa ra chẩn đoán chính thức mang tính phù hợp với hệ thống y tế là điều chỉ bác sĩ tâm thần làm được.', 'Cao', 'Website · Inbox', false, '73'),
  (19, 'Chuyên môn', 'Nhà tâm lý và bác sĩ tâm thần khác nhau thế nào?', 'Nhà tâm lý lâm sàng (Thạc sĩ Tâm lý học Lâm sàng trở lên) được đào tạo để đánh giá sức khỏe tâm thần, nhận diện và phân biệt các rối loạn, đưa ra hướng dẫn hỗ trợ chăm sóc y tế (phối hợp với bác sĩ tâm thần), và thực hành các liệu pháp giúp bạn hiểu và quản lý vấn đề. Bác sĩ tâm thần là người đưa ra chẩn đoán chính thức, kê thuốc và các can thiệp y tế.', 'Cao', 'Website · Inbox', false, null),
  (20, 'Chuyên môn', 'Therapist của Wabi có bằng cấp gì?', 'Hầu hết đội ngũ Wabi là Thạc sĩ Tâm lý học Lâm sàng, tốt nghiệp từ các trường trong nước (ĐHQG Hà Nội, ĐH KHXH&NV) và quốc tế (ĐH Sussex – Anh, ĐH Western Sydney – Úc, Russian State Social University – Nga, ĐH Wrexham – Anh, ĐH Murdoch – Singapore). Nhiều người có 5–7 năm kinh nghiệm thực hành.', 'Cao', 'Website · Inbox', false, null),
  (21, 'Chuyên môn', 'Wabi dùng những liệu pháp nào?', 'Đội ngũ Wabi thực hành đa dạng: CBT (nhận thức – hành vi), DBT (biện chứng hành vi), ACT (chấp nhận & cam kết), Person-Centered (nhân vị trọng tâm), Psychodynamic & Psychoanalysis (tâm động học, phân tâm), IFS (hệ thống gia đình nội tâm), EFT/EFIT (tập trung cảm xúc), Gestalt, MI (phỏng vấn động lực), MBCT/MBSR/MiCBT (chánh niệm), CPT, BA (hoạt hóa hành vi), SFBT (giải pháp ngắn hạn), Art as Therapy.', 'Trung bình', 'Website', false, '81'),
  (22, 'Chọn therapist', 'Làm sao để chọn therapist phù hợp?', 'Chia sẻ với admin về tuổi, nơi sinh sống, vấn đề bạn đang gặp và kỳ vọng của bạn về therapist. Wabi sẽ gợi ý người có chuyên môn khớp nhất — ví dụ có therapist chuyên về attachment styles, có người chuyên PTSD, có người chuyên tâm lý học đường. Bạn cũng có thể nói rõ nếu có preference riêng (giới tính, độ tuổi, phong cách làm việc).', 'Cao', 'Inbox', false, '85'),
  (23, 'Chọn therapist', 'Nếu mình thấy không hợp với therapist thì sao?', 'Bạn hoàn toàn có thể đổi therapist nếu cảm thấy cần thiết. Việc không ''connect'' được với một người không có nghĩa là therapy không hiệu quả với bạn — mối quan hệ trị liệu là yếu tố quan trọng bậc nhất. Nếu có vấn đề gì (khó hiểu, không kết nối được), bạn có thể nhắn admin hoặc feedback trực tiếp cho therapist.', 'Cao', 'Website · Inbox', false, '88'),
  (24, 'Quy trình', 'Tham vấn online hay offline?', 'Cả hai. Các therapist của Wabi làm việc Online qua nền tảng Google Meet, hoặc trực tiếp tại địa điểm của therapist (Hà Nội và TP.HCM). Một số therapist chỉ làm online. 
Các phiên làm việc offline thường có phụ thu thêm do Wabi phải chi trả chi phí thuê phòng tham vấn cho bên thứ ba.', 'Cao', 'Website · Inbox', true, null),
  (25, 'Quy trình', 'Online có hiệu quả bằng offline không?', 'Nhiều nghiên cứu quốc tế cho thấy tham vấn online có hiệu quả tương đương gặp trực tiếp với phần lớn các vấn đề tâm lý phổ biến như lo âu và trầm cảm. Điều quan trọng là bạn có không gian riêng tư và cảm thấy thoải mái. Với một số trường hợp (trẻ nhỏ, khủng hoảng cấp tính), gặp trực tiếp có thể phù hợp hơn.', 'Trung bình', 'Website · Inbox', false, '95'),
  (26, 'Quy trình', 'Mình phải làm bao nhiêu buổi?', 'Tại Wabi không có quy định số buổi bắt buộc cố định. Lộ trình trị liệu sẽ được thiết kế riêng tùy thuộc vào vấn đề, mong muốn và mục tiêu của bạn. Sau buổi gặp đầu tiên, therapist sẽ trao đổi và đề xuất lộ trình phù hợp với bạn. Thông thường, bạn có thể tham khảo khung thời gian phổ biến sau:
- Ngắn hạn (4–6 buổi): Phù hợp để giải quyết các khó khăn cụ thể ở hiện tại, học kỹ năng ứng phó căng thẳng hoặc định hướng vấn đề.
- Trung và dài hạn (12 buổi trở lên): Phù hợp với các tổn thương sâu sắc, các rối nhiễu tâm lý hoặc nhu cầu tái cấu trúc bản thân toàn diện.
- Tần suất linh hoạt: Thường là 1 buổi/tuần ở giai đoạn đầu, sau đó có thể giãn cách ra 2 tuần/buổi hoặc hàng tháng khi tình trạng của bạn đã ổn định.
Bạn luôn là người chủ động quyết định việc tiếp tục, điều chỉnh tần suất hay dừng quá trình trị liệu dựa trên sự bàn bạc và thống nhất với therapist.', 'Cao', 'Website · Inbox', true, 'Câu hỏi: Mình cần tham gia bao nhiêu buổi trị liệu?'),
  (27, 'Quy trình', 'Screening là gì? Vì sao mình phải trả lời?', 'Screening là một bảng câu hỏi ngắn gọn (thường mất 3–5 phút trả lời) được gửi đến bạn trước buổi hẹn chính thức, về tình trạng của bạn hiện tại, các yếu tố nguy cơ, điều khiến bạn lo lắng hay băn khoăn và kỳ vọng về therapist.
Việc hoàn thành screening không chỉ giúp Wabi kết nối bạn với therapist phù hợp mà còn giúp therapist nắm được thông tin ban đầu trước khi bước vào phòng tham vấn, nhận diện sớm các dấu hiệu khủng hoảng nếu có để chuẩn bị phương án hỗ trợ an toàn và kịp thời nhất cho bạn.', 'Cao', 'Inbox', true, null),
  (28, 'Quy trình', 'Wabi gửi lịch qua đâu? Mình cần làm gì?', 'Admin gửi lịch qua email. Nếu Wabi gửi bài test trước buổi, bạn làm xong có thể nhắn admin để therapist xem kết quả trước.', 'Cao', 'Inbox', false, null),
  (29, 'Quy trình', 'Mình muốn đổi lịch thì sao?', 'Bạn nhắn admin muộn nhất trước 3 tiếng so với giờ hẹn. Nếu báo muộn hơn, therapist vẫn tính phí như bình thường. Vì Wabi không thu cọc trước, tụi mình rất mong bạn không huỷ lịch sát giờ.', 'Cao', 'Website · Inbox', false, null),
  (30, 'Quy trình', 'Sau buổi mình nhận được gì?', 'Nếu bạn làm Đánh giá tâm lý: báo cáo chi tiết dạng PDF gửi qua email trong 7–10 ngày. Nếu bạn tham vấn/trị liệu: therapist xây dựng Kế hoạch can thiệp (Treatment Plan); nếu bạn có yêu cầu xem xét, therapist có thể hỗ trợ hoàn thành trong vòng 5 ngày.', 'Cao', 'Website · Inbox', false, '109'),
  (31, 'Quy trình', 'Mình đặt lịch buổi tiếp theo thế nào?', 'Bạn có thể đặt lịch tiếp theo linh hoạt bằng một trong các cách dưới đây:
- Trao đổi trực tiếp với therapist ngay cuối buổi để chốt lịch tuần tới
- Nhắn admin qua Hotline/Zalo/Instagram để được sắp xếp lịch trống mới nhất hoặc đổi therapist nếu bạn cảm thấy cần thiết.', 'Trung bình', 'Website · Inbox', true, null),
  (33, 'Chi phí', 'Wabi có gói ưu đãi không?', 'Có. Gói Đồng Hành: combo 8 buổi trị liệu giảm ngay 10% tổng phí. Lợi ích không chỉ là tiết kiệm chi phí mà còn giúp bạn giữ lịch cố định với chuyên gia, tạo sự ổn định và an tâm trong suốt quá trình. Hướng nghiệp cũng đang có ưu đãi theo gói.', 'Cao', 'Website · Inbox', false, null),
  (36, 'Chi phí', 'Mình không đủ tiền đi therapy thì sao?', 'Wabi có chương trình dành cho bạn ở Hà Nội: uống đủ 10 ly cà phê tại Onion Cafe → được 1 buổi tham vấn tâm lý miễn phí. Ngoài ra, các đường dây nóng miễn phí như Ngày Mai (096 306 1414) hay Tổng đài 111 luôn sẵn sàng lắng nghe bạn.', 'Cao', 'Website · Social', false, null),
  (37, 'Onion Cafe', 'Chương trình 10 ly cà phê là gì?', 'Uống đủ 10 ly cà phê tại Onion Cafe → được 1 buổi tham vấn tâm lý miễn phí. Không phải clickbait — Wabi làm thật. Chương trình dành cho các bạn tại Hà Nội. Wabi biết nhiều người đang cần nói chuyện với ai đó nhưng chưa sẵn sàng, chưa đủ tiền, hoặc chỉ đơn giản là chưa dám. Thì cứ uống cà phê đã, tích từ từ. Ghé Onion Cafe tại 4 Ngõ 46A Phạm Ngọc Thạch, Hà Nội → báo họ tên và số điện thoại khi order → Wabi tích ly tự động cho bạn. Bạn không cần nhớ hay giữ thẻ gì cả.', 'Cao', 'Website · Social', false, null),
  (39, 'Trẻ vị thành niên', 'Dưới 18 tuổi có tham gia được không?', 'Được, nhưng cần có sự đồng ý của phụ huynh. Bạn chỉ cần chụp màn hình đồng ý của phụ huynh và chia sẻ số Zalo của phụ huynh với admin là được.', 'Cao', 'Website · Inbox', false, null),
  (40, 'Trẻ vị thành niên', 'Phụ huynh có được biết nội dung buổi tham vấn không?', 'Có, nhưng ở mức độ phù hợp và tôn trọng nguyên tắc bảo mật của thân chủ. Tại Wabi, sự riêng tư của thân chủ luôn được tôn trọng để các bạn cảm thấy an toàn khi chia sẻ, dù bạn bao nhiêu tuổi. 
Quy trình đồng hành cùng phụ huynh được thực hiện như sau:
- Bảo mật chi tiết cuộc trò chuyện: therapist không tiết lộ chi tiết từng lời nói hay nhật ký, suy nghĩ riêng tư của thân chủ cho phụ huynh, trừ khi có sự đồng ý của thân chủ.
- Cập nhật tiến trình và khuyến nghị cho phụ huynh: therapist sẽ trao đổi với phụ huynh về bức tranh toàn cảnh, sự tiến bộ, cũng như hướng dẫn phụ huynh cách phối hợp, tương tác với thân chủ để hỗ trợ tiến trình phục hồi tốt nhất.
- Ngoại lệ phá vỡ nguyên tắc bảo mật: therapist bắt buộc phải thông báo ngay cho phụ huynh/người giám hộ trong trường hợp phát hiện nguy cơ thân chủ tự hại, gây hại cho người khác hoặc đang trong tình trạng nguy hiểm cấp tính.
Trước khi bắt đầu tiến trình, Wabi/therapist sẽ có một buổi thống nhất rõ ràng về ranh giới bảo mật giữa phụ huynh – thân chủ – nhà trị liệu để tất cả các bên đều cảm thấy an tâm và được tôn trọng.', 'Cao', 'Inbox', true, 'Thêm cụm từ nếu tôi dưới 18 tuổi,...'),
  (41, 'Bảo mật', 'Thông tin của mình có được giữ kín không?', 'Có. Wabi là không gian an toàn, riêng tư và thấu cảm. Mọi thông tin bạn chia sẻ với therapist được bảo mật theo nguyên tắc đạo đức nghề nghiệp. Ngoại lệ hiếm hoi theo chuẩn quốc tế là khi có nguy cơ nghiêm trọng đến tính mạng của bạn hoặc người khác — trong trường hợp đó therapist sẽ trao đổi với bạn trước.', 'Cao', 'Website · Inbox', false, '131'),
  (42, 'Bảo mật', 'Wabi có kê thuốc không?', 'Không. Nhà tâm lý không kê thuốc — đó là việc của bác sĩ tâm thần. Nếu tình trạng của bạn cần can thiệp y tế, Wabi sẽ kết nối bạn với bác sĩ và đánh giá của nhà tâm lý sẽ là cơ sở tốt để bạn trao đổi với bác sĩ.', 'Cao', 'Website · Inbox', false, '134'),
  (43, 'Hiệu quả', 'Bao lâu thì mình thấy khá hơn?', 'Không có câu trả lời chung. Một số người thấy nhẹ hơn ngay sau vài buổi đầu chỉ vì cuối cùng cũng được nói ra; những vấn đề sâu như sang chấn hay khuôn mẫu gắn bó thường cần thời gian dài hơn. Điều quan trọng là bạn và therapist cùng thống nhất mục tiêu và kiểm tra tiến trình định kỳ.', 'Cao', 'Website · Inbox', false, '138'),
  (44, 'Hiệu quả', 'Đi therapy có làm mình ''yếu đuối'' không?', 'Ngược lại. Chủ động tìm đến hỗ trợ đòi hỏi sự dũng cảm và tự nhận thức. Ở nhiều nước, therapy được xem như việc chăm sóc sức khỏe bình thường — giống như đi khám răng hay tập gym cho tinh thần.', 'Trung bình', 'Website · Social', false, '141'),
  (45, 'Hiệu quả', 'Therapist có phán xét mình không?', 'Không. Đội ngũ Wabi làm việc với tinh thần không phán xét, và không gian tham vấn là nơi an toàn để bạn chia sẻ trung thực. Càng cởi mở, therapist càng hiểu đúng tình huống và hỗ trợ đúng hướng.', 'Cao', 'Website · Inbox', false, '144'),
  (46, 'Sau buổi', 'Mình cần làm gì giữa các buổi?', 'Tuỳ liệu pháp, therapist có thể gợi ý bài tập về nhà (ghi nhật ký cảm xúc với CBT, thực hành chánh niệm, hoạt hóa hành vi...). Việc thực hành giữa các buổi thường là yếu tố tạo ra thay đổi thật sự — buổi tham vấn chỉ là 60 phút, còn cuộc sống của bạn là phần còn lại.', 'Trung bình', 'Website · Inbox', false, '148'),
  (47, 'Khẩn cấp', 'Mình đang khủng hoảng, cần giúp ngay thì gọi đâu?', 'Hãy liên hệ ngay: Đường dây nóng Ngày Mai 096 306 1414 · Tổng đài Bảo vệ Trẻ em Quốc gia 111 · Hội Tâm lý Trị liệu Việt Nam 1900 63 644 · Ngôi nhà Bình yên (phụ nữ & trẻ em) 1900 96 96 80 · Bệnh viện Việt Pháp Hà Nội 024 3574 1111. Bạn không phải đối mặt một mình.', 'Cao', 'Website · Inbox', false, null),
  (48, 'Khẩn cấp', 'Wabi có hỗ trợ khẩn cấp 24/7 không?', 'Wabi không phải là dịch vụ cấp cứu và không hoạt động 24/7. Nếu bạn hoặc người thân đang trong tình huống nguy hiểm tức thời, hãy ưu tiên liên hệ các đường dây nóng ở trên hoặc đến cơ sở y tế gần nhất ngay lập tức.', 'Cao', 'Website', false, null),
  (50, 'Quy trình', 'Mình cần chuẩn bị không gian thế nào trước buổi?', 'Buổi online: mở cam và mic trước khi tham gia, có wifi ổn định và một không gian yên tĩnh, riêng tư — nếu chưa thoải mái bạn hoàn toàn có thể tắt cam. Buổi offline: therapist sẽ chờ bạn ở điểm hẹn, bạn vui lòng đến trước 5–10 phút để ổn định chỗ ngồi.', 'Cao', 'Website · Inbox', false, null);
