-- Đồng bộ danh mục dịch vụ 9 mục được duyệt ngày 2026-08-30.
-- Idempotent: có thể chạy lại mà không tạo dòng trùng.

delete from public.services
where name in ('Art Therapy', 'Employment Asssistant Program', 'Mentorship for Future Therapists');

with catalog(sort_order, name, name_en, description, description_en) as (values
  (1, 'Tham vấn & Trị liệu tâm lý', 'Counseling & Psychotherapy', 'Quá trình điều trị liên tục nhằm giải quyết vấn đề tâm lý, cải thiện sức khỏe tinh thần và phát triển cá nhân, thông qua đối thoại và các kỹ thuật chuyên biệt. Phù hợp cho vấn đề về bản ngã (phát triển bản thân, lòng tự trọng, phong cách gắn bó) và các bệnh lý.', 'An ongoing process to address psychological difficulties, improve mental wellbeing and support personal growth, through dialogue and specialized techniques. Suited to questions of self (personal development, self-esteem, attachment style) and clinical conditions.'),
  (2, 'Đánh giá tâm lý', 'Psychological Assessment', 'Sử dụng các bài kiểm tra và công cụ chuẩn hóa để thu thập thông tin về nhận thức, tính cách, cảm xúc và hành vi. Buổi 60 phút làm việc trực tiếp với therapist — họ chọn bài test phù hợp, kết luận ngay trong buổi và gửi báo cáo PDF chi tiết qua email trong 7–10 ngày.', 'Using standardized tests and tools to gather information about cognition, personality, emotion and behavior. A 60-minute session working directly with a therapist — they choose suitable tests, conclude within the session, and send a detailed PDF report by email within 7–10 days.'),
  (3, 'Tham vấn cặp đôi', 'Couple Counseling', 'Cùng nhau xây dựng mối quan hệ tốt đẹp hơn và làm rõ các vấn đề về giao tiếp, cách thể hiện cảm xúc. Buổi đầu khám phá nhu cầu riêng của mỗi người (30 phút/người), các buổi sau cả hai tham gia cùng nhau (90 phút). Có thể sắp xếp buổi riêng khi cần.', 'Build a better relationship together and clarify issues around communication and expressing emotion. The first session explores each person''s needs (30 min/person); later sessions are joint (90 min). Individual sessions can be arranged when needed.'),
  (4, 'Hướng nghiệp', 'Career Counseling', 'Làm test năng lực + trò chuyện với therapist về định hướng. Gói Cơ bản (2 buổi) gồm test và tư vấn kết quả; gói Chuyên sâu (3 buổi) có thêm buổi lên kế hoạch thực hiện định hướng.', 'Take an aptitude test + talk with a therapist about direction. The Basic package (2 sessions) covers testing and results consultation; the In-depth package (3 sessions) adds a session to plan out your direction.'),
  (5, 'Employee Assistance Program (EAP)', 'Employee Assistance Program (EAP)', 'Đồng hành cùng doanh nghiệp trong việc xây dựng văn hóa quan tâm đến con người thông qua các giải pháp chăm sóc sức khỏe tâm thần dựa trên cơ sở khoa học và phù hợp với bối cảnh thực tiễn.', 'Partnering with organizations to build people-centered workplace cultures through evidence-based mental health solutions tailored to real-world organizational contexts.'),
  (6, 'Low-cost Therapy', 'Low-cost Therapy', 'Chương trình Hỗ trợ (Low-cost Therapy) mang đến giải pháp hỗ trợ thiết thực với mức phí giảm 20% so với thông thường, dành riêng cho học sinh và sinh viên dưới 20 tuổi hoặc các bạn đang gặp khó khăn về tài chính.', 'Our Low-cost Therapy program offers practical mental health support at fees 20% lower than standard rates, exclusively for students under 20 or people experiencing financial hardship.'),
  (7, 'Workshop', 'Workshop', 'Chú trọng sự kết hợp giữa lý thuyết nền tảng và thực hành trải nghiệm, giúp bạn mang về những giá trị ứng dụng thực tế. Dưới sự dẫn dắt của thạc sĩ tâm lý/nhà trị liệu, mỗi buổi học sẽ cung cấp kiến thức chuyên ngành và kỹ năng cụ thể—từ thiết lập ranh giới, nhận diện kiểu gắn bó đến xoa dịu lo âu.', 'Combining foundational theory with experiential practice, each workshop gives you practical tools to apply in everyday life. Led by a master''s-level psychologist or therapist, every session offers specialist knowledge and specific skills—from setting boundaries and recognizing attachment styles to easing anxiety.'),
  (8, 'Open Talk', 'Open Talk', 'Không gian trò chuyện bình đẳng, tự do, không diễn giả hay áp lực phát biểu. Bạn có thể thoải mái lắng nghe hoặc lên tiếng khi sẵn sàng. Mỗi phiên thảo luận đều có chuyên viên tâm lý đồng hành để giữ vững không gian an toàn, bảo mật và nâng đỡ cảm xúc.', 'An open, equal conversation space with no speakers and no pressure to contribute. You are welcome to listen or speak when you feel ready. A mental health professional accompanies each discussion to maintain a safe, confidential and emotionally supportive space.'),
  (9, 'Mentorship in Psychology', 'Mentorship in Psychology', 'Chương trình mentorship dành cho sinh viên Tâm lý muốn khám phá ngành tham vấn - trị liệu qua trải nghiệm thực tế, không phải lý thuyết. 6 buổi để bạn đặt chân vào cơ sở tham vấn thật, tự đánh giá bản thân qua trắc nghiệm chuyên môn, và nghe những câu chuyện nghề nghiệp từ người đang làm nghề. Bạn không cần biết trước câu trả lời, chỉ cần mang theo câu hỏi.', 'A mentorship program for psychology students who want to explore counseling and therapy through hands-on experience, not just theory. Across six sessions, you will step inside a real counseling center, reflect on your fit through professional assessments, and hear career stories directly from practitioners. You do not need to have the answers—just bring your questions.')
)
update public.services as service set
  sort_order = catalog.sort_order,
  name_en = catalog.name_en,
  description = catalog.description,
  description_en = catalog.description_en
from catalog
where service.name = catalog.name;

with catalog(sort_order, name, name_en, description, description_en) as (values
  (1, 'Tham vấn & Trị liệu tâm lý', 'Counseling & Psychotherapy', 'Quá trình điều trị liên tục nhằm giải quyết vấn đề tâm lý, cải thiện sức khỏe tinh thần và phát triển cá nhân, thông qua đối thoại và các kỹ thuật chuyên biệt. Phù hợp cho vấn đề về bản ngã (phát triển bản thân, lòng tự trọng, phong cách gắn bó) và các bệnh lý.', 'An ongoing process to address psychological difficulties, improve mental wellbeing and support personal growth, through dialogue and specialized techniques. Suited to questions of self (personal development, self-esteem, attachment style) and clinical conditions.'),
  (2, 'Đánh giá tâm lý', 'Psychological Assessment', 'Sử dụng các bài kiểm tra và công cụ chuẩn hóa để thu thập thông tin về nhận thức, tính cách, cảm xúc và hành vi. Buổi 60 phút làm việc trực tiếp với therapist — họ chọn bài test phù hợp, kết luận ngay trong buổi và gửi báo cáo PDF chi tiết qua email trong 7–10 ngày.', 'Using standardized tests and tools to gather information about cognition, personality, emotion and behavior. A 60-minute session working directly with a therapist — they choose suitable tests, conclude within the session, and send a detailed PDF report by email within 7–10 days.'),
  (3, 'Tham vấn cặp đôi', 'Couple Counseling', 'Cùng nhau xây dựng mối quan hệ tốt đẹp hơn và làm rõ các vấn đề về giao tiếp, cách thể hiện cảm xúc. Buổi đầu khám phá nhu cầu riêng của mỗi người (30 phút/người), các buổi sau cả hai tham gia cùng nhau (90 phút). Có thể sắp xếp buổi riêng khi cần.', 'Build a better relationship together and clarify issues around communication and expressing emotion. The first session explores each person''s needs (30 min/person); later sessions are joint (90 min). Individual sessions can be arranged when needed.'),
  (4, 'Hướng nghiệp', 'Career Counseling', 'Làm test năng lực + trò chuyện với therapist về định hướng. Gói Cơ bản (2 buổi) gồm test và tư vấn kết quả; gói Chuyên sâu (3 buổi) có thêm buổi lên kế hoạch thực hiện định hướng.', 'Take an aptitude test + talk with a therapist about direction. The Basic package (2 sessions) covers testing and results consultation; the In-depth package (3 sessions) adds a session to plan out your direction.'),
  (5, 'Employee Assistance Program (EAP)', 'Employee Assistance Program (EAP)', 'Đồng hành cùng doanh nghiệp trong việc xây dựng văn hóa quan tâm đến con người thông qua các giải pháp chăm sóc sức khỏe tâm thần dựa trên cơ sở khoa học và phù hợp với bối cảnh thực tiễn.', 'Partnering with organizations to build people-centered workplace cultures through evidence-based mental health solutions tailored to real-world organizational contexts.'),
  (6, 'Low-cost Therapy', 'Low-cost Therapy', 'Chương trình Hỗ trợ (Low-cost Therapy) mang đến giải pháp hỗ trợ thiết thực với mức phí giảm 20% so với thông thường, dành riêng cho học sinh và sinh viên dưới 20 tuổi hoặc các bạn đang gặp khó khăn về tài chính.', 'Our Low-cost Therapy program offers practical mental health support at fees 20% lower than standard rates, exclusively for students under 20 or people experiencing financial hardship.'),
  (7, 'Workshop', 'Workshop', 'Chú trọng sự kết hợp giữa lý thuyết nền tảng và thực hành trải nghiệm, giúp bạn mang về những giá trị ứng dụng thực tế. Dưới sự dẫn dắt của thạc sĩ tâm lý/nhà trị liệu, mỗi buổi học sẽ cung cấp kiến thức chuyên ngành và kỹ năng cụ thể—từ thiết lập ranh giới, nhận diện kiểu gắn bó đến xoa dịu lo âu.', 'Combining foundational theory with experiential practice, each workshop gives you practical tools to apply in everyday life. Led by a master''s-level psychologist or therapist, every session offers specialist knowledge and specific skills—from setting boundaries and recognizing attachment styles to easing anxiety.'),
  (8, 'Open Talk', 'Open Talk', 'Không gian trò chuyện bình đẳng, tự do, không diễn giả hay áp lực phát biểu. Bạn có thể thoải mái lắng nghe hoặc lên tiếng khi sẵn sàng. Mỗi phiên thảo luận đều có chuyên viên tâm lý đồng hành để giữ vững không gian an toàn, bảo mật và nâng đỡ cảm xúc.', 'An open, equal conversation space with no speakers and no pressure to contribute. You are welcome to listen or speak when you feel ready. A mental health professional accompanies each discussion to maintain a safe, confidential and emotionally supportive space.'),
  (9, 'Mentorship in Psychology', 'Mentorship in Psychology', 'Chương trình mentorship dành cho sinh viên Tâm lý muốn khám phá ngành tham vấn - trị liệu qua trải nghiệm thực tế, không phải lý thuyết. 6 buổi để bạn đặt chân vào cơ sở tham vấn thật, tự đánh giá bản thân qua trắc nghiệm chuyên môn, và nghe những câu chuyện nghề nghiệp từ người đang làm nghề. Bạn không cần biết trước câu trả lời, chỉ cần mang theo câu hỏi.', 'A mentorship program for psychology students who want to explore counseling and therapy through hands-on experience, not just theory. Across six sessions, you will step inside a real counseling center, reflect on your fit through professional assessments, and hear career stories directly from practitioners. You do not need to have the answers—just bring your questions.')
)
insert into public.services (sort_order, name, name_en, description, description_en)
select catalog.*
from catalog
where not exists (
  select 1 from public.services where services.name = catalog.name
);
